### ISSUE TITLE
Fire Trigger Action Done, no Message no Log

### ISSUE THREAD

**Issue by msmarziali** [ableev/Zabbix-in-Telegram#102]
Hi,
I installed zabbix 3.2 and Zabbix in Telegram.
From shell if I run:   
` ./zbxtg_group.py SGMNMS testo "$(echo -e 'zbxtg;graphs: \nzbxtg;graphs_period=3600\nzbxtg;graphs_width=700\nzbxtg;graphs_height=300\nzbxtg;itemid:102584\nzbxtg;title:ololo')"`
the notification and graph work successful!.

The problem is:
From zabbix web frontend I created an item vfs.file.exists[/tmp/test.txt] and a trigger that check the existence of the file: {sgmzabnms01:vfs.file.exists[/tmp/test.txt].last()}=0.

When trigger occurs the dashboard reports show "Done" the action was performed:
![1](https://user-images.githubusercontent.com/2008688/34276907-c49be9ba-e6a3-11e7-96f1-0d1292d0c245.jpg)

In my Telegram Group SGMNMS,  the message does not arrive and I look in the log file zabbix_server.log (DebugLevel 4) but I can not find anything written about sending the message/notification.

The following figures show my configuration:
- Media Type
![media](https://user-images.githubusercontent.com/2008688/34277267-468b68f0-e6a5-11e7-9b77-364fa150cd24.jpg)

- Actions
![action](https://user-images.githubusercontent.com/2008688/34277577-b0c86a6e-e6a6-11e7-9c81-11b554a7ec2c.jpg)

- Actions operations
![action_operations](https://user-images.githubusercontent.com/2008688/34277303-614d71e2-e6a5-11e7-8da8-f90781b3b0e2.jpg)

- User Media
![user_media](https://user-images.githubusercontent.com/2008688/34277319-74ffd41e-e6a5-11e7-8f06-2e2860f5cc55.jpg)

Can you give me directions, I'm wrong all?
Thanks for the time dedicated to me

Regards,
Massimiliano.

**Comment by ableev** [comment]
Start from "From shell if I run" and compare it to https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line
I see the difference between them.

**Comment by ableev** [comment]
By the way, the best and fastest way to get help – http://t.me/ZbxTg group in Telegram
