### ISSUE TITLE
Uppercase in username doesn't accept.

### ISSUE THREAD

**Issue by AlexGluck** [ableev/Zabbix-in-Telegram#105]
Example AlexGluck not working, but in lowercase alexgluck accepted properly

**Comment by AlexGluck** [comment]
May be i mistake and problem not in uppercase ```zbxtg.py: {u'ok': True, u'result': [{u'message': {u'date': 1517238693, u'text': u'\u044b\u0432\u0430', u'from': {u'username': u'AlexGluck', u'first_name': u'Alex', u'last_name': u'Gluck', u'is_bot': False, u'language_code': u'ru', u'id': 165524748}, u'message_id': 7438, u'chat': {u'username': u'AlexGluck', u'first_name': u'Alex', u'last_name': u'Gluck', u'type': u'private', u'id': 165524748}}, u'update_id': 895120881}, {u'message': {u'date': 1517238775, u'text': u'zxc', u'from': {u'username': u'AlexGluck', u'first_name': u'Alex', u'last_name': u'Gluck', u'is_bot': False, u'language_code': u'ru', u'id': 165524748}, u'message_id': 7439, u'chat': {u'username': u'AlexGluck', u'first_name': u'Alex', u'last_name': u'Gluck', u'type': u'private', u'id': 165524748}}, u'update_id': 895120882}, {u'message': {u'date': 1517238971, u'text': u'sdf', u'from': {u'username': u'AlexGluck', u'first_name': u'Alex', u'last_name': u'Gluck', u'is_bot': False, u'language_code': u'ru', u'id': 165524748}, u'message_id': 7440, u'chat': {u'username': u'AlexGluck', u'first_name': u'Alex', u'last_name': u'Gluck', u'type': u'private', u'id': 165524748}}, u'update_id': 895120883}]}
zbxtg.py: User 'alexgluck' needs to send some text bot in private```

**Comment by ableev** [comment]
@AlexGluck the Telegram documentation says that "Usernames are case-insensitive".
So I don't think that it's right to equalize uppercase and lowercase nicknames in third-party software.
If someone wants to change something in their username - he should update alerts as well.
