### ISSUE TITLE
needs to send some text bot in private

### ISSUE THREAD

**Issue by tangjiaxing669** [ableev/Zabbix-in-Telegram#107]
```shell
[root@zabbix Zabbix-in-Telegram]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
[root@zabbix Zabbix-in-Telegram]# 
[root@zabbix Zabbix-in-Telegram]# zabbix_get -V
zabbix_get (Zabbix) 3.0.14
Revision 76338 27 December 2017, compilation time: Dec 27 2017 16:18:54

Copyright (C) 2017 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

[root@zabbix Zabbix-in-Telegram]# cat zbxtg_settings.py
# -*- coding: utf-8 -*-

tg_key = "***"  # telegram bot api key

zbx_tg_prefix = "zbxtg"  # variable for separating text from script info
zbx_tg_tmp_dir = "/var/tmp/" + zbx_tg_prefix  # directory for saving caches, uids, cookies, etc.
zbx_tg_signature = False

zbx_tg_update_messages = True
zbx_tg_matches = {
    "problem": "PROBLEM: ",
    "ok": "OK: "
}

zbx_server = "http://192.168.0.11/zabbix/"  # zabbix server full url
zbx_api_user = "admin"
zbx_api_pass = "zabbix"
zbx_api_verify = True  # True - do not ignore self signed certificates, False - ignore

zbx_basic_auth = False
zbx_basic_auth_user = "admin"
zbx_basic_auth_pass = "zabbix"

proxy_to_zbx = None
proxy_to_tg = None

#proxy_to_zbx = "proxy.local:3128"
#proxy_to_tg = "proxy.local:3128"

google_maps_api_key = None  # get your key, see https://developers.google.com/maps/documentation/geocoding/intro

zbx_tg_daemon_enabled = False
zbx_tg_daemon_wl_ids = [6931850, ]
zbx_tg_daemon_wl_u = ["ableev", ]

zbx_db_host = "localhost"
zbx_db_database = "zabbix"
zbx_db_user = "zbxtg"
zbx_db_password = "zbxtg"


emoji_map = {
    "OK": "✅",
    "PROBLEM": "❗",
    "info": "ℹ️",
    "WARNING": "⚠️",
    "DISASTER": "❌",
    "bomb": "",
    "fire": "",
    "hankey": "",
}
```

The results of my test are as follows：

```
[root@zabbix Zabbix-in-Telegram]# ./zbxtg.py "@tom_jason" test test --debug
zbxtg.py: {u'ok': True, u'result': {u'username': u'tom_jason_bot', u'first_name': u'tom_jason', u'is_bot': True, u'id': 512075454}}
zbxtg.py: Cache file with uids: /var/tmp/zbxtg/uids.txt
zbxtg.py: Getting uid from /getUpdates...
zbxtg.py: https://api.telegram.org/bot512075454:AAGWtAX882rjhYiG3tGkRPzrMiKPgWJwn6M/getUpdates
zbxtg.py: Content of /getUpdates:
zbxtg.py: {u'ok': True, u'result': []}
zbxtg.py: User 'tom_jason' needs to send some text bot in private
```

But my TG received no news, who can help. 
Thanks.

**Comment by ableev** [comment]
@tangjiaxing669 do it as it says

**Comment by SteveKeller** [comment]
I have the same problem, but with some messages already written to the bot..

Messages are show with the --debug flag in the output.

curl request with api key of the bot works and get alle the messages back..

**Comment by SteveKeller** [comment]
I have found the problem..

Some people like me doesn't have a username in telegram, only surname and lastname.

This is my return result from the telegram api:

`"ok": true,                    
"result": [                    
  {                            
    "update_id": 123456789,    
    "message": {               
      "message_id": 2,         
      "from": {                
        "id": 123456789,       
        "is_bot": false,       
        "first_name": "Steve", 
        "last_name": "Keller", 
        "language_code": "de"  
      },                       
      "chat": {                
        "id": 123456789,       
        "first_name": "Steve", 
        "last_name": "Keller", 
        "type": "private"      
      },                       
      "date": 1518037377,      
      "text": "hi"             
    }                          
  },                           `

In the python script "zbxtg.py" there is only a check for a username to get the "uid" and not for the combination of firstname and lastname.

This is the part in the get_uid function:
`if "username" in chat:
                  if chat["username"] == name:
                      uid = chat["id"]`

after i changed these 3 lines of code to:

`uid = chat["id"]`

it worked for me :)

**Comment by ableev** [comment]
@SteveKeller it is not secure, I am not willing to make such changes, sorry.
