### ISSUE TITLE
zbxtg.py: User '{ALERT:SENDTO}' needs to send some text bot in private

### ISSUE THREAD

**Issue by Arjoni** [ableev/Zabbix-in-Telegram#113]
I keep getting this error: zbxtg.py: User '{ALERT:SENDTO}' needs to send some text bot in private

I am on latest version of Zabbix and I have configured everything as the tutorial says.

**Comment by kodesmon** [comment]
Hi Arjoni

The receiver must start a conversation with the bot, like 'Hi bot', then the bot can send the information.

Regards,

Ricardo P

**Comment by ableev** [comment]
@Arjoni , the right macro is "{ALERT.SENDTO}", not "{ALERT:SENDTO}".

**Comment by ridwansoursop** [comment]
> @arjoni , the right macro is "{ALERT.SENDTO}", not "{ALERT:SENDTO}".
I already did as you say, but mine still showing such error. 
I have tried send some message.
But if I do thru commandline i can be delivered.
Do you mind to help me?


![image](https://user-images.githubusercontent.com/55168155/76946394-8f353200-6936-11ea-9d27-710f2fe782ce.png)

![image](https://user-images.githubusercontent.com/55168155/76946080-0d450900-6936-11ea-8ac1-aa43fc556eec.png)

**Comment by derdeagle** [comment]
Pay attention to the spelling ;)
`{AELERT.SENDTO}` contains on "E" too much.
Use `{ALERT.SENDTO}` instead. ;)

**Comment by ridwansoursop** [comment]
> Pay attention to the spelling ;)
> `{AELERT.SENDTO}` contains on "E" too much.
> Use `{ALERT.SENDTO}` instead. ;)

Thank you, omg i didnt know that
