### ISSUE TITLE
Interactive bot

### ISSUE THREAD

**Issue by klez22** [ableev/Zabbix-in-Telegram#114]
Hello !
Could you explain, how to make an interactive bot put answer to commands in a group chat, not in private chat?

Could you explain what affects the following parameters : 
zbx_tg_daemon_enabled_users 
zbx_tg_daemon_enabled_chats

p.s. основной вопрос в том, как заставить бота отвечать в групповой чат. Он упорно отвечает в private, не зависимо от того, откуда ему пишешь, с группового или private чата

**Comment by ableev** [comment]
There is no such feature yet.

**Comment by ableev** [comment]
The main issue is #53
