### ISSUE TITLE
Wrong graph period on some graphs

### ISSUE THREAD

**Issue by rootbdfy** [ableev/Zabbix-in-Telegram#118]
Hello.
Basically everything works fine, but in rare cases there is a problem with graphs:
https://prnt.sc/j15xlr
but problem solved in 10:11:09 .

**Comment by ableev** [comment]
@rootbdfy And how should I guess what was the input? 
There is no start and end time, only the period, and the calculates from "now - period".
The screenshot indicates that you received the graph about the *problem*. Everything is fine.
So?

**Comment by rootbdfy** [comment]
You right. I'm fooled, sorry for this )
Everything work fine.
Thank you!
