### ISSUE TITLE
socks5 proxy support

### ISSUE THREAD

**Issue by ableev** [ableev/Zabbix-in-Telegram#119]
The script should be working through socks5 proxy, right now only http/https proxy is working

**Comment by ableev** [comment]
https://github.com/ableev/Zabbix-in-Telegram/wiki/Proxy – recommended article

**Comment by Realmagnum** [comment]
It is not working on Zabbix virtual appliance Ubuntu 14.04.3.
`sudo pip install requests --upgrade`
_Collecting urllib3<1.24,>=1.21.1 (from requests)
Installing collected packages: urllib3, chardet, certifi, requests
Found existing installation: urllib3 1.7.1_
**Cannot uninstall 'urllib3'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**

**Comment by Realmagnum** [comment]
Another way - create proxy-pass on VPS. [Like here](
https://toster.ru/q/522971#comment_1642440)
And change 
 tg_url_bot_general = "https://api.telegram.org/bot"
with your own server.
 tg_url_bot_general = "https://mydomain.org/bot"
