### ISSUE TITLE
Error "Connection not allowed by ruleset" with socks5 proxy

### ISSUE THREAD

**Issue by rustavy** [ableev/Zabbix-in-Telegram#122]
#
# sudo pip freeze | grep -iE 'sock|req'
PySocks==1.6.8
requests==2.18.4
requests-oauthlib==0.6.2
requests-toolbelt==0.8.0
#
# python zbxtg.py "99-999" "ololo" "{{OK}} ololo" --group
Traceback (most recent call last):
  File "zbxtg.py", line 890, in <module>
    main()
  File "zbxtg.py", line 802, in main
    tg.send_message(uid, zbxtg_body_text)
  File "zbxtg.py", line 90, in send_message
    answer = requests.post(url, params=params, proxies=self.proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot${API_KEY}/sendMessage?text=ololo+%E2%9C%85+ololo%0A--group&disable_notification=False&chat_id=${Private_chat_id}%0A&disable_web_page_preview=False (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f4739a11510>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
#
# curl -sL --socks5-hostname cc.bb.aa:9999 --proxy-user uuu:pppp https://api.telegram.org | wc -l
431
#
# curl -sL --socks5-hostname cc.bb.aa:9999 --proxy-user uuu:pppp https://api.telegram.org/bot${API_KEY}/getupdates
{"ok":true,"result":[]}
#
#
# curl -sL --socks5 cc.bb.aa:9999 --proxy-user uuu:pppp https://api.telegram.org/bot${API_KEY}/getupdates | wc
      0       0       0
#

**Comment by rustavy** [comment]
# -*- coding: utf-8 -*-

tg_key = "${API_KEY}"  # telegram bot api key

zbx_tg_prefix = "zbxtg"  # variable for separating text from script info
zbx_tg_tmp_dir = "/var/tmp/" + zbx_tg_prefix  # directory for saving caches, uids, cookies, etc.
zbx_tg_signature = False

zbx_tg_update_messages = True
zbx_tg_matches = {
    "problem": "PROBLEM: ",
    "ok": "OK: "
}

zbx_server = "http://127.0.0.1/zabbix/"  # zabbix server full url
zbx_api_user = "TelEm"
zbx_api_pass = "password"
zbx_api_verify = False #True  # True - do not ignore self signed certificates, False - ignore
#zbx_api_verify = True  # True - do not ignore self signed certificates, False - ignore

zbx_basic_auth = False
zbx_basic_auth_user = "TelEm"
zbx_basic_auth_pass = "password"

proxy_to_zbx = None
proxy_to_tg = "socks5://uu:ppp@cc.bb.aa:9999"

# proxy_to_zbx = "http://proxy.local:3128"
# proxy_to_tg = "https://proxy.local:3128"

# proxy_to_tg = "socks5://user1:password2@hostname:port" # socks5 with username and password
# proxy_to_tg = "socks5://hostname:port" # socks5 without username and password

google_maps_api_key = None  # get your key, see https://developers.google.com/maps/documentation/geocoding/intro

zbx_tg_daemon_enabled = False
zbx_tg_daemon_wl_ids = [-999999999, ]
zbx_tg_daemon_wl_u = ["99-999", ]

zbx_db_host = "localhost"
zbx_db_database = "zabbix"
zbx_db_user = "zbxtg"
zbx_db_password = "zbxtg"


emoji_map = {
    "OK": "✅",
    "PROBLEM": "❗",
    "info": "ℹ️",
    "WARNING": "⚠️",
    "DISASTER": "❌",
    "bomb": "💣",
    "fire": "🔥",
    "hankey": "💩",
}

**Comment by ableev** [comment]
@rustavy "Connection not allowed by ruleset" shows that your proxy server doesn't allow you to use it for such domain

**Comment by rustavy** [comment]
Strangely, the curl claims the opposite and the telegram too

**Comment by ableev** [comment]
@rustavy I don't know what is uuu ppp and cc bb aa, so it's not the bot problem, and it's better to find out what is wrong with your proxy by yourself

**Comment by ableev** [comment]
I think it's not related to script or python, something strange with proxy, nothing to fix
