### ISSUE TITLE
command line  /usr/lib/zabbix/alertscripts/zbxtg.py  on zabbix 3.4

### ISSUE THREAD

**Issue by wifi75** [ableev/Zabbix-in-Telegram#125]
hello script not work after send this command 

 /usr/lib/zabbix/alertscripts/zbxtg.py "test" "hello" "how are you?"

error:

Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 9, in <module>
    import requests
ImportError: No module named requests
[Exit 1]

any solution?

**Comment by justabaka** [comment]
Install the Python library named Requests

**Comment by wifi75** [comment]
Ok now we have install on my centos 7 with command  "pip install requests"
but I have same problem
