### ISSUE TITLE
From Zabbix the messages is partially sends raw

### ISSUE THREAD

**Issue by XAOc57** [ableev/Zabbix-in-Telegram#126]
From Zabbix the messages is partially sends raw.
For example:
Title:
`{{{TRIGGER.SEVERITY}}} Problem`
Body:
```
Last: {ITEM.VALUE1} ({TIME})
zbxtg;graphs
zbxtg;graphs_period=1800
zbxtg;itemid:{ITEM.ID1}
zbxtg;title:{HOST.HOST} — {TRIGGER.NAME}
zbxtg;debug
zbxtg;channel
Level: {TRIGGER.SEVERITY}
Host: {HOSTNAME} ({HOST.IP})
Description:
{TRIGGER.DESCRIPTION}
```
In Telegram comes (note: no graphs!):
```
{{High}} Problem
Last: 1 (13:12:10)
zbxtg;graphs
zbxtg;graphs_period=1800
zbxtg;itemid:24550
zbxtg;title:my.server.com — Amount ssh sessions
zbxtg;debug
zbxtg;channel
Level: High
Host: my.server.com (12.12.15.22)
Description:
(my bad, haven't description)
```
But if I send a message from the console:
`sudo -u zabbix /path/to/script/zbxtg.py MY_ID {{OK}}{{WARNING}} "$(echo -e '{{OK}}\nzbxtg;graphs: \nzbxtg;graphs_period=3600\nzbxtg;itemid:24550\nzbxtg;title:OLOLO')"`
Then everything is fine.
Of course, if I use the -e flag in echo, the emoji will work, but the graphs themselves will not work. And on title {{OK}}{{WARNING}} works without -e flag.

**My settings:**
I use socks5 proxy with authorization
Zabbix 3.0.7 on Debian Stretch.

**zbxtg_settings:**
```
tg_key = "my-bot-api-key"  # telegram bot api key

zbx_tg_prefix = "zbxtg"  # variable for separating text from script info
zbx_tg_tmp_dir = "/var/tmp/" + zbx_tg_prefix  # directory for saving caches, uids, cookies, etc.
zbx_tg_signature = False
zbx_tg_update_messages = True
zbx_tg_matches = {
    "problem": "PROBLEM: ",
    "ok": "OK: "
}
zbx_server = "http://127.0.0.1/zabbix/"  # zabbix server full url
zbx_api_user = "botuser"
zbx_api_pass = "botpassword"
zbx_api_verify = True  # True - do not ignore self signed certificates, False - ignore

zbx_basic_auth = False
zbx_basic_auth_user = ""
zbx_basic_auth_pass = ""

proxy_to_zbx = None
#proxy_to_tg = None

# proxy_to_zbx = "http://proxy.local:3128"
# proxy_to_tg = "https://proxy.local:3128"

proxy_to_tg = "socks5://user:password@proxy_server_ip:port" # socks5 with username and password
# proxy_to_tg = "socks5://hostname:port" # socks5 without username and password
google_maps_api_key = None  # get your key, see https://developers.google.com/maps/documentation/geocoding/intro
zbx_tg_daemon_enabled = False
zbx_tg_daemon_wl_ids = [6931850, ]
zbx_tg_daemon_wl_u = ["null", ]

zbx_db_host = "localhost"
zbx_db_database = "zabbix_db"
zbx_db_user = "zabbix_user"
zbx_db_password = "zabbix_password"

emoji_map = {
    "OK": "✅",
    "PROBLEM": "❗",
    "info": "ℹ️",
    "WARNING": "⚠️",
    "DISASTER": "❌",
    "bomb": "💣",
    "fire": "🔥",
    "hankey": "💩",
}
```
Screenshots:
https://imgur.com/a/jYa0Flt

===========
Для русскоязычных пользователей, кратко:
Отправка с сервера Zabbix в Телеграм происходит частично в raw-формате.
Вместо эмодзи, уровня проблемы, приходят имена самих переменных.
Вместо графиков, просто переменные объявляющие график.
Подставляются переменные: имени тригера, имени хоста и его адреса.
Но если я отправляю эти сообщения через bash в консоли, то они уходят как положено, вместе с графиками и эмодзи. Разумеется, при использовании ключа -e в echo, эмодзи будут работать, но графики сами по себе благодаря ключу -e не заработают. И в шапке, никаких -e ключей не используется, а вместо переменных подставляются эмодзи, как положено.
Я использую socks5 прокси с авторизацией
Zabbix 3.0.7 на Debian 9 Stretch.
Мой конфиг бота выше.
Скриншоты примеров (те, что были под рукой) https://imgur.com/a/jYa0Flt

**Comment by ableev** [comment]
Why is it "partly"? 
Where is successful sending of messages?

**Comment by XAOc57** [comment]
If i send test message from the console on server:
```
sudo -u zabbix zbxtg.py \
MY_ID \
{{OK}}{{WARNING}} \
"$(echo -e '{{OK}}\nzbxtg;graphs: \nzbxtg;graphs_period=3600\nzbxtg;itemid:24550\nzbxtg;title:OLOLO')"
```
Then come on Telegram:
Emoji on title: ok and warning
and emoji on body: ok
and graph item id: 24550, with title: OLOLO

But, if test message from zabbix server:
Title:`{{OK}}{{WARNING}}`
Body:
```
{{OK}}
zbxtg;graphs: 
zbxtg;graphs_period=3600
zbxtg;itemid:{ITEM.ID1}
zbxtg;title:{HOST.HOST} — {TRIGGER.NAME}
```


Come on Telegram:
```
{{OK}}{{WARNING}}
{{OK}}
zbxtg;graphs: 
zbxtg;graphs_period=3600
zbxtg;itemid:ITEM_ID
zbxtg;title:MY.HOST — MY.TRIGGER_NAME
```
No graph! And no emoji! Instead Emoji -- {{OK}}, {{WARNING}}, etc...

**Comment by XAOc57** [comment]
Works!
Thanks to all!

1. I made a mistake in users media (old sender telegram instead zbxtg)
2. In my emoji map there were no variables I needed, for example, **high**.
