### ISSUE TITLE
No action found in zabbix

### ISSUE THREAD

**Issue by wifi75** [ableev/Zabbix-in-Telegram#127]
Hello the manual script work , I receive message  on my telegram, but whrn I try to make same problem for send message, no action found on my zabbix server, though I make on zabbix new user with telegram @users.

It is very strange... some idea?

**Comment by ableev** [comment]
@wifi75 I don't understand what do you mean. 
https://github.com/ableev/Zabbix-in-Telegram/wiki/Report-problem-how-to

**Comment by wifi75** [comment]
Yes, 
th command line work: 
 /usr/lib/zabbix/alertscripts/zbxtg.py "myuser_telegram" "hello" "test message"

when I try this I receice messang on telegram.
But anything from zabbix gui interface.

**Comment by wifi75** [comment]
![1](https://user-images.githubusercontent.com/31816231/39926180-ab8da8ec-552e-11e8-8992-7ca263329554.JPG)
![2](https://user-images.githubusercontent.com/31816231/39926190-b11f6ac0-552e-11e8-84d8-ab508d92aef8.JPG)
![3](https://user-images.githubusercontent.com/31816231/39926193-b4391e2c-552e-11e8-8580-a76e3eb7b348.JPG)
![4](https://user-images.githubusercontent.com/31816231/39926196-b6ef77ce-552e-11e8-81a8-b2a18abd1755.JPG)

**Comment by ableev** [comment]
It has nothing to do with script.
Setup your actions correctly. 
Check users' or groups' rights.
