### ISSUE TITLE
Acknowledge Message doesnt work

### ISSUE THREAD

**Issue by dennismettler** [ableev/Zabbix-in-Telegram#130]
Hi Everyone

i really enjoy this script and it's just working fine. Problem and Resolve Messages are arriving my Telegram Account.

The only thing that doesnt work is the acknowledgement messages. If i acknowledge a problem, then zabbix sends an E-Mail which is working fine but the Telegram Messages doesnt arrive in this case. The Zabbix log says the message is sent successfuly.
![photo_2018-05-15_21-26-35](https://user-images.githubusercontent.com/39314684/40079012-ad7236fe-5886-11e8-8e3b-6d6a0d1e918a.jpg)

**Comment by ableev** [comment]
@Zeekra please, show me the action

**Comment by Zeekra** [comment]
Sure. Here we go
![action](https://user-images.githubusercontent.com/39314684/41190596-50dac234-6be2-11e8-99c9-2128bfb80ce5.png)
![media](https://user-images.githubusercontent.com/39314684/41190597-50f4170c-6be2-11e8-9aaf-f64fa2191966.png)

**Comment by ableev** [comment]
@Zeekra , thanks! I'll check

**Comment by palamarchuknv** [comment]
Привет друзья. У меня такая же проблема была. Я пытался оставить комментарий или закрыть проблему со своей учетной записи. Но у меня не приходили уведомления подтверждения в телеграмм. Поэтому я попробовал закрыть проблему с учетной записи администратора и все получилось. Я просто создал еще одну учетку и на нее посадил все уведомления. И Все заработало.

**Comment by apfiuza** [comment]
Poderia detalhar mais o solução que você aplicou no seu servicor?

**Comment by ableev** [comment]
@palamarchuknv , thanks.
@dennismettler , probably there is nothing wrong with the script: https://support.zabbix.com/browse/ZBX-15345
