### ISSUE TITLE
zbxtg.py: User 'brony' needs to send some text bot in private

### ISSUE THREAD

**Issue by Axcendio** [ableev/Zabbix-in-Telegram#132]
Hi Ableev,

I followed the instructions. 
1) Copy all the necessary phython scripts  to zabbix alertscript folder (including updating the zbxtg_setting.py with API of a bot which I created for test)
2) created a media based on it
3) and then created a user (for testing as below)
![image](https://user-images.githubusercontent.com/33312438/40699881-7962b36e-6409-11e8-8854-7961f8e804a2.png)

But I still feel like I am missing something.
When I tested sending a message to the test user called brony (which is essentially myself) I keep getting these messages:
./zbxtg.py "@brony" "test" "testing" --debug
zbxtg.py: {u'ok': True, u'result': {u'username': u'TestSubject001bot', u'first_name': u'Test001', u'is_bot': True, u'id': 596111054}}
zbxtg.py: Cache file with uids: /var/tmp/zbxtg/uids.txt
Trying to read cached uid for brony, private, from /var/tmp/zbxtg/uids.txt
zbxtg.py: Getting uid from /getUpdates...
zbxtg.py: https://api.telegram.org/bot596111054:AAH7NJ4u9rCfr0xkJckjxwCT8rwGGGjA1nI/getUpdates
zbxtg.py: Content of /getUpdates:
zbxtg.py: {u'ok': True, u'result': [{u'message': {u'date': 1527650125, u'text': u'Hello', u'from': {u'username': u'coffeecaplemon', u'first_name': u'Brony', u'is_bot': False, u'id': 441580288, u'language_cod  e': u'en-US'}, u'message_id': 5, u'chat': {u'username': u'coffeecaplemon', u'first_name': u'Brony', u'type': u'private', u'id': 441580288}}, u'update_id': 83423446}]}
zbxtg.py: User 'brony' needs to send some text bot in private

Could you help to point to where I am wrong please?

**Comment by Axcendio** [comment]
Forgot to add that I have sent a "Hello" message to my bot.
But the error still persist.

**Comment by ableev** [comment]
@Axcendio are you sure that your username is "brony"? As I see from your logs it's "coffeecaplemon". Don't mix "name" with "username".
