### ISSUE TITLE
Could not sent message to group

### ISSUE THREAD

**Issue by zhukovnv84** [ableev/Zabbix-in-Telegram#135]
I follow documentation 
https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line

Testing simple text, group chats
./zbxtg_group.py "Zabbix in Telegram" test test
and got zbxtg_group.py: You need start a conversation with your bot first in 'Zabbix in Telegram' group chat, type '/start@talkerzabbixbot'

- how i created bot talkerzabbixbot
in Botfather
 /newbot
talkerzabbix
talkerzabbixbot
Done! Congratulations on your new bot...
- find  talkerzabbixbot - press start

- bot is added to my group
-  type message in group /start@talkerzabbixbot - nothing to give. bot is not answer.
- in zbxtg_settings.py added tg_key = "xxxx03392:AAFuq6jMYqGVoU7PUn0q_6WoEHkzHMuZsCc"  # telegram bot api key

all is working file with ./zbxtg.py - it is sent messages to my bot, but not to group
thanks for advice

**Comment by zhukovd** [comment]
You need replace "zabbix in telegram" name of your group (register sensitive) and add --group to end command
example:
./zbxtg.py Name_your_group test test --group
use --debug for more information

**Comment by zhukovnv84** [comment]
Thanks!
