### ISSUE TITLE
 Problems with the interactive bot.

### ISSUE THREAD

**Issue by vring0** [ableev/Zabbix-in-Telegram#136]
Hello! I sent the / hosts command to the interactive bot after that it does not start. An error occurred while starting the bot.

Привет! отправил интерактивному боту команду /hosts после этого он не запускается. Ошибка при запуске бота.

Traceback (most recent call last):
  File "./ZbxTgDaemon.py", line 215, in <module>
    main()
  File "./ZbxTgDaemon.py", line 179, in main
    if m["message"]["from"]["id"] not in zbxtg_settings.zbx_tg_daemon_wl_ids:
KeyError: 'message'

**Comment by ableev** [comment]
@vring0 the script has been rewritten, try again, please
