### ISSUE TITLE
zbxtg.py stopped working, error 104 - Connection reset by peer

### ISSUE THREAD

**Issue by highlandy** [ableev/Zabbix-in-Telegram#140]
Hi!

Suddenly zbxtg.py stopped to send notifications. Manual debug for old script and for up-to-date version is attached. 

https://gist.github.com/highlandy/77c8d98a59968eb465a006c18ccf41f6 - old
https://gist.github.com/highlandy/575dbca14973c0ef6e3accb6bae550ed - new

**Comment by highlandy** [comment]
Already checked, it's fine. How do I know where exactly connection is dropped?

**Comment by ableev** [comment]
check the availability of api.telegram.org

**Comment by highlandy** [comment]
It's available.

```
telnet api.telegram.org 443
Trying 5.3.3.17...
Connected to api.telegram.org.
Escape character is '^]'.
```

Going to test connection via proxy, will let you know.

**Comment by highlandy** [comment]
You were right, something in between blocked messed connection.

Using new script via proxy resolved my issue, thank you for supporting!
