### ISSUE TITLE
Still no graphs  on telegram from zabbix4.0.1 

### ISSUE THREAD

**Issue by coeus-lei** [ableev/Zabbix-in-Telegram#146]
I cant get graphs  from zabbix to telegram

**Comment by coeus-lei** [comment]
![image](https://user-images.githubusercontent.com/42054370/48967358-fd573680-f019-11e8-955f-c00f2eca20b5.png)

**Comment by coeus-lei** [comment]
![image](https://user-images.githubusercontent.com/42054370/48967363-0a742580-f01a-11e8-954a-313d360c0f5f.png)

**Comment by coeus-lei** [comment]
These things I sent on the command line and received messages in the telegram

**Comment by ableev** [comment]
https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line

**Comment by coeus-lei** [comment]
Thank  you again！  I already sucessd






在 2018-11-27 16:21:12，"Ilya Ableev" <notifications@github.com> 写道：


Closed #146.
