### ISSUE TITLE
Simple way to send messages to group

### ISSUE THREAD

**Issue by ableev** [ableev/Zabbix-in-Telegram#15]
Now you need to add special flag "zbxtg;chat".
Has to be simpler.

**Comment by camillagds** [comment]
Put in the README.md this information.
Thank you very much ;)

**Comment by ableev** [comment]
@camillagds I already did, "Configuration / Installation" part.

**Comment by rimametal** [comment]
Hi,
I could not use the zbxtg_group.py, would you please help me to and give me a hint.

**Comment by ableev** [comment]
@rimametal provide more info, see article in wiki https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line

**Comment by rimametal** [comment]
would you please check the content of zbxtg_group.py?
with current content (just 1 line) here is the result:
# ./zbxtg_group.py "Zabbix in Telegram" test test
./zbxtg_group.py: line 1: zbxtg.py: command not found

**Comment by ableev** [comment]
@rimametal there is no content, it is just symbolic link to `zbxtg.py`.

**Comment by rimametal** [comment]
so, is it mean that I have to copy the content of "zbxtg.py" to "zbxtg_group.py"?

**Comment by rimametal** [comment]
with same content in both file:

./zbxtg_group.py "Zabbix in Telegram" test test
: No such file or directory

**Comment by ableev** [comment]
@rimametal pull the code again, and make sure that `zbxtg_group.py` is symbolic link to `zbxtg.py `

**Comment by rimametal** [comment]
Thanks a lot, Group messaging start working.
But because of my poor knowledge of python and scripting, now I have issue with sending graph to Telegram, copied your mentioned action to Zabbix, but not working while original Zabbix action working well and send text messages to Telegram!

**Comment by ableev** [comment]
@rimametal you don't need to known python.
Check the article: https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line I've added record about graphs.

**Comment by rimametal** [comment]
Thanks.
No success yet, I tested everything based on the wiki and send a graph through CLI and works well, but when using action, nothing send! any idea?

**Comment by ableev** [comment]
Check zabbix_server.log
Check if selinux is enabled.

**Comment by rimametal** [comment]
Thanks a lot.
It was a problem with /tmp folder access.
Its a great Zabbix Plug-in.

**Comment by rimametal** [comment]
Did you ever works on Two way communication with Zabbix using Telegram Bot?
For example when you receive a Trigger Alert, send a message to the Bot to acknowledge that event.

**Comment by ableev** [comment]
@rimametal I thought about that, but you need to keep you bot available via public web url, most of zabbix servers are running in local network.

**Comment by rimametal** [comment]
My Zabbix installation have access to public network as well as private one, so If you have the files ready I can test it.

**Comment by ableev** [comment]
I think that original idea was implemented. 
Any other enhancements will be available for zabbix 3.x.

**Comment by itjwd-works** [comment]
Hi ableev,

Hope you are well!

I'm still getting this message

> zbxtg.py: User 'userName' needs to send some text bot in private

I sent /start and send also message to my bot, and I still received that error.

Thank you!

**Comment by MengLeangSN** [comment]
Hi i'm young of zabbix
I'm try to configure like below 
https://github.com/ableev/Zabbix-in-Telegram
but not working 
please help me
thank!

**Comment by bazwalt** [comment]
same issues here
