### ISSUE TITLE
Direct Messages work fine - Group Messages do not.

### ISSUE THREAD

**Issue by bazwalt** [ableev/Zabbix-in-Telegram#156]
Here is the output I get in the failure:

Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/zbxtg_group.py", line 909, in <module>
main()
File "/usr/lib/zabbix/alertscripts/zbxtg_group.py", line 793, in main
tg.update_cache_uid(zbx_to, str(uid).rstrip())
File "/usr/lib/zabbix/alertscripts/zbxtg_group.py", line 213, in update_cache_uid
with open(self.tmp_uids, "a") as cache_file_uids:
IOError: [Errno 13] Permission denied: '/var/tmp/zbxtg/uids.txt'

I've assigned r+w to /var/tmp/zbxtg/uids.txt and chowned to zabbit.

I've tried using both the name of my group and also the Group ID but neither makes a difference.

I'm pulling my hair trying to work out whats wrong.

Interestingly, if I use the group ID it tells me i need to start a conversation using the /start command but doing so makes no difference either.

**Comment by ableev** [comment]
@bazwalt I can't reproduce the issue without the input.
I'm not a magician. 
Please, provide full input and output. 

P.S. check the SELinux or something like that in your system.

**Comment by aminvakil** [comment]
@bazwalt Try this
`sudo chcon -u system_u -t lib_t /usr/lib/zabbix/alertscripts/*`
