### ISSUE TITLE
No permissions to referred object or it does not exist

### ISSUE THREAD

**Issue by rforberger** [ableev/Zabbix-in-Telegram#157]
Hi,
I get the error in TG "No permissions to referred object or it does not exist".

My API user, configured as `zbx_api_user` in `zbxtg_settings.py`, has Zabbix Admin rights and I can access the `.../zabbix/graphs.php` site using this user in the browser.

I am using Zabbix 4.x on FreeBSD amd64.

Any ideas what could be the problem?

Thanks in advance.

Best regards,
Ronny

**Comment by ableev** [comment]
@rforberger follow this manual: https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line

**Comment by rforberger** [comment]
@ableev 
Thanks for your reply.
The problem was the user (```zbx_api_user```), which does not have the permission to access the graph item. I set the ```zbx_api_user``` to `admin` now and I am getting graphs now.

But I don't want to give the `zbxtg.py` script the full admin access to Zabbix, so what rights does the api user have to have, in order to display graphs?

Thanks in advance.

Best regards,
rforberger

**Comment by ableev** [comment]
Grant read-only rights for all hosts to a user.
