### ISSUE TITLE
Report feature request

### ISSUE THREAD

**Issue by zappbrannigan34** [ableev/Zabbix-in-Telegram#160]
Daily or weekly report like widget "Problem hosts" by cron

**Comment by ableev** [comment]
@zappbrannigan34 so what's the problem? Create the report and send it via the script.

**Comment by zappbrannigan34** [comment]
example?

**Comment by ableev** [comment]
```
./report.sh > /tmp/report.txt
zbxtg.py @username "Report" "$(cat /tmp/report.txt)"
```

**Comment by zappbrannigan34** [comment]
zabbix report is graphics

**Comment by zappbrannigan34** [comment]
https://www.zabbix.com/integrations/pdf

**Comment by ableev** [comment]
So? Create by yourself.
I'm not "I want something, do it for free for me" guy.

**Comment by zappbrannigan34** [comment]
its feature request, not pr

**Comment by ableev** [comment]
It will never be implemented here
