### ISSUE TITLE
Разметка в сообщения.

### ISSUE THREAD

**Issue by AlexandrGII** [ableev/Zabbix-in-Telegram#162]
День добрый!
У нас в имени хоста используется нижнее подчеркивание К Примеру "GPON_Cleo"
Обычный скрипт отправки сообщения в телегу работает нормально:
![norm_markdown](https://user-images.githubusercontent.com/26869234/55418271-fec1de00-557a-11e9-8d71-82f24fcf8c33.JPG)
При отправке с помощью вашего скрипта, все после _ переходит в курсив до следующего _ После него все в норме.  

![markdown](https://user-images.githubusercontent.com/26869234/55418164-c1f5e700-557a-11e9-8397-c2fde194c2a6.JPG)

Как можно исправить данную ситуацию?

**Comment by ableev** [comment]
Не используйте markdown
