### ISSUE TITLE
Needs to send some text bot in private on zabbix test

### ISSUE THREAD

**Issue by villitax** [ableev/Zabbix-in-Telegram#168]
Hello friend, I have a problem with the zabbix and telegram application. the test works correctly, ""./zbxtg.py "@alber_hedima" "first part of a message" "second part of a message" --debug"" but when I try it on zabbix, I get the message that I need to write a private message.

Media type test failed.
zbxtg.py: User ' alber_hedima' needs to send some text bot in private

also fails to put @alber_hedima

Thanks!!

**Comment by djettah** [comment]
I have the same problem but with a group chat:

zbxtg.py: User '-391537009' needs to send some text bot in private

**Comment by ableev** [comment]
@villitax I don't know what you did to get such an error. Try this: https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line
The issues are not meant to answer to every person who did not set up the script correctly.

**Comment by ableev** [comment]
@djettah , it's not the same problem. 
Please, read the README once again. 
You've done it wrong.
