### ISSUE TITLE
Interactive bot - Run bot, in infinite loop

### ISSUE THREAD

**Issue by alexalburca** [ableev/Zabbix-in-Telegram#173]
Hello

I apologize to everyone for my lack of knowledge, is when you do not know where else to consult, I'm at this stage.

I am trying to keep the interactive bot always running and when it presents problems I made a sh script for it to restart. All this is new to me and the script causes it to stop responding and open the script several times.

I would like to know if someone has the script to leave the interactive bot in a loop, or even a link where I can consult how to do it the right way.

Admin, sorry to deviate a little from the subject.

**Comment by denser** [comment]
Use cron every second?

**Comment by ableev** [comment]
You can use `tmux` or `screen` utility.
