### ISSUE TITLE
Documentation: Media Type needs parameters

### ISSUE THREAD

**Issue by Signum** [ableev/Zabbix-in-Telegram#175]
Please note in the documentation that newer Zabbix versions require you to add these parameters for a "Script" Media Type:

* {ALERT.SENDTO}
* {ALERT.SUBJECT}
* {ALERT.MESSAGE}

So the settings need to look like this:

![image](https://user-images.githubusercontent.com/36562/60814560-24700c00-a196-11e9-952d-3ad2254e9528.png)

**Comment by ableev** [comment]
1. Open "main" page, scroll down
2. Open link: https://github.com/ableev/Zabbix-in-Telegram/wiki/Working-with-Zabbix-3.0

What's the problem?

**Comment by Signum** [comment]
Oh, I see. I was confused by the fact that I run Zabbix 4. So I didn't bother checking the link for Zabbix 3.

**Comment by Signum** [comment]
You didn't fix it though. It still says "Note that Zabbix 3.0 has different settings for that step". So Zabbix 4.x users will still be confused.
