### ISSUE TITLE
No error but meccage never comes. 

### ISSUE THREAD

**Issue by rmalenko** [ableev/Zabbix-in-Telegram#189]
Hello
After I had met this error `Bad Request: group chat was upgraded to a supergroup chat` I changed 
`/var/tmp/zbxtg/uids.txt` to properly id and I am able to send a message to group from the command line 
`sudo -u zabbix ./zbxtg.py "Boot_Server_Alerts" "Relax, this is test message :)" "I haven't a new message for you" --debug --group`

However, Zabbix doesn't have an error but a message never coming.
![image](https://user-images.githubusercontent.com/1563560/71515425-c7832200-28ab-11ea-82a8-d0faf0dc44bf.png)

Could you help and prompt how to I can debug this, please?

**Comment by ableev** [comment]
https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line
