### ISSUE TITLE
Readme update - making py executable 

### ISSUE THREAD

**Issue by StarT3** [ableev/Zabbix-in-Telegram#19]
I think it should be mentioned in Read me file.
Before trying to send anything with Zabbix, we should make zbxtg.py executable.
chmod +x zbxtg.py

**Comment by ableev** [comment]
It is already executable:
```
12:00:28 [reLosted] /tmp $ git clone https://github.com/ableev/Zabbix-in-Telegram.git
Cloning into 'Zabbix-in-Telegram'...
remote: Counting objects: 203, done.
remote: Total 203 (delta 0), reused 0 (delta 0), pack-reused 203
Receiving objects: 100% (203/203), 44.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (107/107), done.
Checking connectivity... done.
12:00:33 [reLosted] /tmp $ cd Zabbix-in-Telegram
12:00:36 [reLosted] /tmp/Zabbix-in-Telegram $ ls -la zbxtg.py
-rwxr-xr-x  1 lost  wheel  11591 Feb 10 12:00 zbxtg.py
12:00:39 [reLosted] /tmp/Zabbix-in-Telegram $
```

**Comment by StarT3** [comment]
Oh, i just copy-pasted .py contents in newly created files. And tested with "python zbxtg.py". It took me 30 minutes to understand why Zabbix could not send me anything while tests are going well.
Ok, if you think it should not be mentioned, let it be.
