### ISSUE TITLE
Not receive messages in Telegram(

### ISSUE THREAD

**Issue by TonyNoIT** [ableev/Zabbix-in-Telegram#192]
Hello
Everything works not with Zabbix
<img width="643" alt="Screenshot 2020-01-07 at 16 14 11" src="https://user-images.githubusercontent.com/58567087/71906095-c08cc700-3169-11ea-9b27-ddab060358cf.png">
Inside Zabbix - the same
<img width="656" alt="Screenshot 2020-01-07 at 16 14 56" src="https://user-images.githubusercontent.com/58567087/71906146-d1d5d380-3169-11ea-8b81-9c9e3aa9def9.png">
<img width="1419" alt="Screenshot 2020-01-07 at 16 12 10" src="https://user-images.githubusercontent.com/58567087/71906165-d8fce180-3169-11ea-92f2-429584c146a1.png">

As i understand - Zabbix run script, but in Telegram - nothing
In Zabbix log - nothing, here `zbx_tg_tmp_dir = "/var/lib/zabbix/" + zbx_tg_prefix  # directory for saving caches, uids, cookies, etc.` nothing.

**Comment by ableev** [comment]
https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line

**Comment by TonyNoIT** [comment]
All this things works
<img width="643" alt="Screenshot 2020-01-07 at 16 14 11" src="https://user-images.githubusercontent.com/58567087/71907829-1ca51a80-316d-11ea-90e8-d6decc6cc0d6.png">

**Comment by ableev** [comment]
Read the doc.

**Comment by TonyNoIT** [comment]
Sorry, but i read and test many times - text arrives in Telegram in this way. 

> In case of success you will see no errors and you will get your message.

**Comment by TonyNoIT** [comment]
<img width="1329" alt="Screenshot 2020-01-07 at 16 57 55" src="https://user-images.githubusercontent.com/58567087/71908975-465f4100-316f-11ea-9ec0-c51eeb09a371.png">

**Comment by TonyNoIT** [comment]
ok - sorry
Add to readme this plz

> Идем в Администрирование — Способы оповещений, жмем кнопку «Создать способ оповещений». В поле «Имя» вводим название способа оповещения. В поле «Тип» нужно выбрать «Скрипт». В поле «Имя скрипта» нужно указать имя файла-скрипт, без пути; например, zbxtg.py В поле «Параметры скрипта» нужно нажать «Добавить» 3 раза и ввести в появившиеся поля {ALERT.SENDTO}, {ALERT.SUBJECT} и {ALERT.MESSAGE}.
