### ISSUE TITLE
Alert and graphic in the same message ? 

### ISSUE THREAD

**Issue by lasilva19** [ableev/Zabbix-in-Telegram#197]
I haved configured the send of alerts with Telegram using the script "Zabbix-in-Telegram": https://github.com/ableev/Zabbix-in-Telegram.
But, I want know if is posible that the script send the graphic in the same message of alert and how I can do this. Today, the script  send the graphic after the alert and in a second message.

**Comment by hardwareadictos** [comment]
+1 on this

**Comment by Varrkan82** [comment]
@hardwareadictos @lasilva19 RTFM.
`zbxtg;single_message`
