### ISSUE TITLE
the bot does not send a graph((

### ISSUE THREAD

**Issue by exden** [ableev/Zabbix-in-Telegram#198]
1. When the trigger is triggered, the bot sends a message, but there is no graph.
2. I did all the testing. everything works except Graphs.
The URL, username and password are correct. Checked by going to the web interface. Using the link in the test http://192.168.222.111//chart3.php?period=3600&name=ololo&width=900&height=200&graphtype=0&legend=1&items[0][itemid]=23706&items[0][sortorder]=0&items[0][drawtype]=5&items[0][color]=00CC00 , the graph is displayed correctly, but it does not come in a telegram
3.
Test private message  https://pastebin.com/XBHyQxNa 
Test group message    https://pastebin.com/5b0kasEL
zbxtg_settings.py         https://pastebin.com/Fm6Eav5w
Test Graphs Message  https://pastebin.com/9nGTkwqb
Validate server's URL   https://pastebin.com/KQKRAyHA
4.
![image](https://user-images.githubusercontent.com/61587041/75580622-29613300-5a79-11ea-80ee-02e730d2b7dd.png)
![image](https://user-images.githubusercontent.com/61587041/75580703-472e9800-5a79-11ea-9f2c-c37250bf5801.png)
![image](https://user-images.githubusercontent.com/61587041/75580792-6f1dfb80-5a79-11ea-80be-a5eae9e7d3c4.png)
![image](https://user-images.githubusercontent.com/61587041/75580896-970d5f00-5a79-11ea-81c7-5fd82dfac743.png)

**Comment by ableev** [comment]
Those tests are useless.(((

**Comment by exden** [comment]
what other data do you need? I will do
