### ISSUE TITLE
Zabbix 3.0 issues

### ISSUE THREAD

**Issue by rlex** [ableev/Zabbix-in-Telegram#20]
...Не отправляется у меня через тройку. Остальные похожие скрипты работают.
Во первых, readme требует апдейта, в тройке аргументы кастомизируются и по дефолту пустые. Старое поведение - это надо сделать вот так:
<img width="528" alt="screen shot 2016-02-17 at 2 28 22 pm" src="https://cloud.githubusercontent.com/assets/84462/13108275/1a44ac3c-d583-11e5-928c-3e05ceb807dc.png">
Так или иначе, у меня не взлетело. Я накидал тупейший скрипт для проверки что заходит в аргументы:
```bash
echo "====" >> /tmp/check_args
echo "$1" >> /tmp/check_args
echo "====" >> /tmp/check_args
echo "$2" >> /tmp/check_args
echo "====" >> /tmp/check_args
echo "$3" >> /tmp/check_args
echo "====" >> /tmp/check_args
```
Вывод:
```
====
@UserName
====
FAIL: PROBLEM: Some server down
====
Last value: 0 (11:20:43)
zbxtg;graphs
zbxtg;graphs_period=10800
zbxtg;itemid:23752
zbxtg;title:host.name.here - Some server down
====
```
Те аргументы нормально парсятся системой. 
Простой ./zbxtg @somerandomusername test test уходит нормально. А вот из заббикса уходить не хочет.

**Comment by ableev** [comment]
@rlex в логах заббикс сервера чего-нибудь есть? Ребята прикручивали к 3, всё было нормально, ничем, кроме параметров – не отличается.

**Comment by ableev** [comment]
Но я погляжу

**Comment by rlex** [comment]
@ableev в логах вообще ничего не вижу относительно запуска скриптов. В action log есть вывод о том, что скрипт завершился с exit-кодом 0, те отработал корректно.

**Comment by rlex** [comment]
Отправляется нормально с одной строкой в ALERT.MESSAGE. Больше не хочет.

**Comment by Gasoid** [comment]
работает у меня норм, только приходит в случае восстановления тоже сообщение о проблеме,

**Comment by vasilevdmitry** [comment]
Тоже поставил 3 зяблик и не присылает ничего. :( 
А если с командной строки, то все отлично..

**Comment by diarworld** [comment]
Если вы сначала запускали скрипт вручную, например от рута, то для работы скрипта после этого необходимо поменять права на папку и файлы в tmp директории:
`chown -R zabbix:zabbix /tmp/zbxtg`
Можно также просто удалить эту директорию. После этого все заработает.

**Comment by rlex** [comment]
@diarworld не помогает, к сожалению. С шаблоном из примера (где графики) не отправляет ничего. Вернул одну строку в сообщение - заработало.

**Comment by ableev** [comment]
@diarworld с вашего позволения, я поправлю немного по-другому, чуть позже.
@rlex вчера протестировал – работает на третьей версии. Добавил несколько параметров. Обновлю код, проверим.

**Comment by ableev** [comment]
Доку проапдейтил, создал отдельную статью https://github.com/ableev/Zabbix-in-Telegram/wiki/Working-with-Zabbix-3.0
