### ISSUE TITLE
zbxtg in zabbix 5

### ISSUE THREAD

**Issue by starlessboi** [ableev/Zabbix-in-Telegram#202]
Hi
I just tested new Zabbix media in telegram 5.0
it's awesome, thanks
I have a question, How can we use proxy in new media type? I mean in previous version, in zbxtg setting we could use proxy..how we can use this feature in new format?

**Comment by hardwareadictos** [comment]
So, you confirm that Zabbix-in-Telegram addon works on Zabbix 5 without issues? :)

**Comment by derdeagle** [comment]
As of now you cannot send images.
But Telegram via the webhook works like a charm for text messages as far as I can tell.

**Comment by hardwareadictos** [comment]
Will wait for the addon to be updated before jumping from Zabbix 4.0 to 5.0 as i like graph integration on telegram and its very useful to me, thanks!

**Comment by ableev** [comment]
@hardwareadictos no one mentioned that before.

**Comment by hardwareadictos** [comment]
> @hardwareadictos no one mentioned that before.

Sorry @ableev , but mentioned what?

**Comment by starlessboi** [comment]
> So, you confirm that Zabbix-in-Telegram addon works on Zabbix 5 without issues? :)

Yeah, for Text messages, It's Okay

**Comment by hardwareadictos** [comment]
> > So, you confirm that Zabbix-in-Telegram addon works on Zabbix 5 without issues? :)
> 
> Yeah, for Text messages, It's Okay

I mean about this add-on. I know zabbix has a new webhook for text messages. Are you referring to it?

**Comment by hardwareadictos** [comment]
Well guys, just updated my 4.0 LTS installation to 5.0 LTS and this addon is still working. I still receive my triggers on telegram with its graphs perfectly. Didn't have to reconfigure anything. Just implemented new server config.

**Comment by olekovin** [comment]
Hm... that's strange, coz I get a "Timeout while executing a shell script" and don't know how to fix this.

Using 5.0 LTS.
Python3 (created alias and symlink to "python")

Any ideas?)

**Comment by hardwareadictos** [comment]
> Hm... that's strange, coz I get a "Timeout while executing a shell script" and don't know how to fix this.
> 
> Using 5.0 LTS.
> Python3 (created alias and symlink to "python")
> 
> Any ideas?)

Only thing I did was update zabbix server and agents. Rear it I just adapted zabbix_server.conf just to have it inline with the conf I had on the old 4.0 LTS. It's not a false positive or coincidence. It's working fine for 5 hours now. Even I restarted all my server environment to test it. Working fine.

With the error you provided maybe it's something local on the server you are executing the python scripts. 

Feel free to ask me whatever you need.

**Comment by olekovin** [comment]
Oh.. the problem isn't so deep, as I think)

Previously I set up IPv6 for my Zabbix server, so when zbxtg.py was tried to resolve api.telegram.org, it's got a v6 address, instead of v4, but server drops any v6 connection except HTTP and HTTPS because I configured that.

So I just do:
ip6tables -I INPUT -s api.telegram.org --dports 88 -j ACCEPT
ip6tables -I INPUT -s api.telegram.org --dports 8443 -j ACCEPT

And all works great :)
