### ISSUE TITLE
Can't send message to a group where my bot belongs to

### ISSUE THREAD

**Issue by Zamana** [ableev/Zabbix-in-Telegram#206]
Hello!

I was able to install and configure zbxtg.py to send messages to my bot. Thanks!

The only issue I'm having for almost a day is that I can't send a message to a group where my bot belongs. Every time I got the following error:
"zbxtg.py: User '-100999(...)999' needs to send some text bot in private"

As I'm able to send message to the group using the web method (https://api.telegram.org/bot<token>/sendMessage?chat_id=<group chat id >&text=<our text>), but not by using zbxtg.py, I'm considering that the Telegram part is fine.

I already change the zbx_tg_tmp_dir variable to a folder where the zabbix user has read/write access, and already tried to use the zbxtg_group.py script (which is just a symlink, but that's ok).

Our Zabbix is the 4.4 version. The group is public.

Anybody can help me with this, please?

Thanks.
Regards.

**Comment by artemrogov** [comment]
Такая же фигня) Да еще у меня и группа приватная))

**Comment by Zamana** [comment]
I decided to use another Telegram implementation for Zabbix and suceeded.

Thanks.
