### ISSUE TITLE
Implement another parameter to specify self.type (private|group)

### ISSUE THREAD

**Issue by derdeagle** [ableev/Zabbix-in-Telegram#21]
Hi @ableev 

Your scripts works like a charm!
But since I want to avoid updating the same scripts for the private and group type I implemented a fourth parameter which is optional and checked  for validity.

**Comment by ableev** [comment]
Hello, @derdeagle. Actually, {{zbxtg_group.py}} is symbolic link, which means that you don't need to update both files, only {{zbxtg.py}}.

**Comment by derdeagle** [comment]
You're absolutely right but the type is hardcoded to "private". If I want to send messages to private chats and groups I need to copy the script and hardcode the type to "group" there, don't I?

**Comment by ableev** [comment]
@derdeagle don't.
`zbxtg.py` - it's one big code, without copies or something. It's just one file, you don't need to update `zbxtg_group.py` because it must be sym link to `zbxtg.py`.

**Comment by derdeagle** [comment]
I see, you check the file name and if it is *zbxtg_group.py* you set the type to **group**. Since this is quite static would you mind changing it / having someone else change it to a more dynamic way?

**Comment by ableev** [comment]
@derdeagle I don't agree with your way of setting that parameter, according to changes in Zabbix 3.0.
We already have #20 about new parameters in zabbix web ui configuration. I'll change the code a bit later, but in another way, if you don't mind.
Thanks for feedback!

**Comment by derdeagle** [comment]
Of course! Go ahead. I'll check it out as soon as it is committed.

**Comment by n3oru** [comment]
Dear friends,

First of all thank you for the great work.

When I'm tring to send message from zabbit to the private telegram channel (not group) I recieve an error:

> zbxtg_group.py: You need to mention your bot in 'test_chan' group chat (i.e. type @YourBot)

Mentioning %botname% in this channel did't do anything. 
Also script sends to the group chat without any kind of problems.

When I have found file: `tmp_uids = tmp_dir + "/uids.txt"`

It consists of:
```
test_nick;private;196561591
test_group;group;-1001010219811
name;type;id
```
So I have changed known and working groups id to id of my private channel (how to find id of private channel - [stackoverflow](http://stackoverflow.com/questions/33858927/how-to-obtain-the-chat-id-of-a-private-telegram-channel)) and it's worked for me! 

> ./zbxtg_group.py test_group 123 123

When I'm trying to send to test_group script is sending to my private channel with id -1001010219811. It's a little bit dirty hack, but it works perfectly.

Hope this will help.
Kind regards,
Aleksey

**Comment by ableev** [comment]
@n3oru what are you trying to say? I don't get it.
Mention is only need to store chat_id, because it will expire in bot's updates after a while.

**Comment by n3oru** [comment]
As I can understand there are four tipes of groups in Telegram:
- Public group ( can be searched and entered, for everyone)
- Private group ( private link needed to enter and participate in group)
- Public channel ( can be searched and entered, only administrators can
write to chat, another people read-only )
- Private channel ( private link needed to enter, only administrators can
write to chat, another people read-only )

I'm speaking about channels. Script can't broadcast to channel (bot added
as administrator), if you give to the script channel_id or channel_name.
Please look at example in my first message.

But if you edit this file and change channel_id of known to the
script group - massages are starting to broadcast in any kind of channels
(public/private).

суббота, 20 февраля 2016 г. пользователь Ilya Ableev написал:

> @n3oru <https://github.com/n3oru> what are you trying to say? I don't get
> it.
> Mention is only need to store chat_id, because it will expire in bot's
> updates after a while.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ableev/Zabbix-in-Telegram/issues/21#issuecomment-186438651>
> .
>


-- 
Григорьев Алексей

**Comment by n3oru** [comment]
As I can understand there are four tipes of groups in Telegram:
- Public group ( can be searched and entered, for everyone)
- Private group ( private link needed to enter and participate in group)
- Public channel ( can be searched and entered, only administrators can
write to chat, another people read-only )
- Private channel ( private link needed to enter, only administrators can
write to chat, another people read-only )

I'm speaking about channels. Script can't broadcast to channel (bot added
as administrator), if you give to the script channel_id or channel_name.
Please look at example in my first message.

But if you edit this file and change channel_id of known to the
script group - massages are starting to broadcast in any kind of channels
(public/private).

**Comment by ableev** [comment]
@n3oru as I can see, there is no difference between "public group" and "private group" for bots. So nothing needs to be changed. 
I'll add channels support in #23.

**Comment by ableev** [comment]
Done, `--debug` parameter, can be used in web ui, see https://github.com/ableev/Zabbix-in-Telegram/wiki/Working-with-Zabbix-3.0
