### ISSUE TITLE
Can't enable graphs in telegram notification

### ISSUE THREAD

**Issue by rahaalizade** [ableev/Zabbix-in-Telegram#212]
Hello,
I used this tutorial for creating my telegram notification but I didn't receive graphs in my alerts that were sent in telegram
This is the result I got:
```
zbxtg;graphs
zbxtg;itemid:42901
```
It's a hardcoded message!
Can anyone help me with this?

**Comment by unnilennium** [comment]
was able to get graphs until September 16th 2021, since then it is just displaying text.
I used to have 2 messages :  
- one witht he text
- one with the graph

I now get 3 time the one with he text.

**Comment by ableev** [comment]
@fatemealizade you need to learn about macros https://www.zabbix.com/documentation/current/en/manual/appendix/macros/supported_by_location
