### ISSUE TITLE
Sending messages to the telegram channel

### ISSUE THREAD

**Issue by SD3vEng** [ableev/Zabbix-in-Telegram#213]
Good afternoon! Can you tell me how to send messages to the telegram channel by a bot? I tried to make it both public and private, I always get one error zbxtg.py : User '-1001703375540' needs to send some text bot in private
The readme talks about some kind of dirty-hack, but I couldn't find any information on it

**Comment by SD3vEng** [comment]
Via the api and https://community.particle.io/t/particle-telegram-bot/59482 the bot sends messages, but why doesn't the script work out

**Comment by fu11p0w3r** [comment]
> Good afternoon! Can you tell me how to send messages to the telegram channel by a bot? I tried to make it both public and private, I always get one error zbxtg.py : User '-1001703375540' needs to send some text bot in private The readme talks about some kind of dirty-hack, but I couldn't find any information on it

Hello. Try using with --channel

**Comment by ableev** [comment]
https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-send-message-to-the-group-chat
It says that you need to use group's name, not chatid.
