### ISSUE TITLE
IMAGE_PROCESS_FAILED

### ISSUE THREAD

**Issue by rlex** [ableev/Zabbix-in-Telegram#25]
Выдает мне тут такое при отправке сообщения с графиком:
```
zbxtg.py: {u'error_code': 400, u'ok': False, u'description': u'[Error]: IMAGE_PROCESS_FAILED'}
```

Куда копать?

**Comment by rlex** [comment]
Ок, кажется нашел.
в .png файле обнаружился html с окном логина.

**Comment by ableev** [comment]
@rlex должно. Авторизация бы не прошла, кука бы не выдалась. Обновитесь до последней версии.

**Comment by rlex** [comment]
Был на https://github.com/ableev/Zabbix-in-Telegram/commit/3cb6d2793fe108ed70dc7606f5a0b8c2a3c98586

Логин-пароль подправил, все ок стало. Но до этого писало PNGшку с HTML внутри.

**Comment by ableev** [comment]
@rlex ```
zbxtg.py: authorization has failed, url: http://127.0.0.1//
zbxtg.py: Login to Zabbix web UI has failed, check manually...
```
Поменял на левые логины-пароли.
