### ISSUE TITLE
In zbxgt.sh script parameter to send to chat should be "zbxtg;chat" but not a "zbxtg;channel"

### ISSUE THREAD

**Issue by Varrkan82** [ableev/Zabbix-in-Telegram#30]
From a script code:
```
TG_CHAT=0 # send message to chat or to private chat to user
METHOD="txt" # sendMessage (simple text) or sendPhoto (attached image)

echo "${BODY}" | grep -q "${ZBX_TG_PREFIX};graphs" && METHOD="image"
echo "${BODY}" | grep -q "${ZBX_TG_PREFIX};chat" && TG_CHAT=1
echo "${BODY}" | grep -q "${ZBX_TG_PREFIX};debug" && ISDEBUG="TRUE" 
```

**Comment by Varrkan82** [comment]
```
TG_CHAT=0 # send message to chat or to private chat to user
METHOD="txt" # sendMessage (simple text) or sendPhoto (attached image)

echo "${BODY}" | grep -q "${ZBX_TG_PREFIX};graphs" && METHOD="image"
echo "${BODY}" | grep -q "${ZBX_TG_PREFIX};chat" && TG_CHAT=1
echo "${BODY}" | grep -q "${ZBX_TG_PREFIX};debug" && ISDEBUG="TRUE"
```

PS: Did you still support this .sh script version?

**Comment by ableev** [comment]
Ok, thank you for report. I don't understand what you wanted to say in title, but obviously bash script has to be the same as python script.
@Varrkan82 yes, but in minor priority.

**Comment by Varrkan82** [comment]
Sorry. This report more about annotations in your HOWTO. I've spent a few hours to make a script work with a wrong instruction. :)

> Annotations
> 
> zbxtg;graphs -- enables attached graphs
> zbxtg;graphs_period=10800 -- set graphs period (default - 3600 seconds)
> zbxtg;graphs_width=700 -- set graphs width (default - 900px)
> zbxtg;graphs_height=300 -- set graphs height (default - 300px)
> zbxtg;itemid:{ITEM.ID1} -- define itemid (from trigger) for attach
> zbxtg;title:{HOST.HOST} - {TRIGGER.NAME} -- graph title
> zbxtg;debug -- enables debug mode, some logs and images will be saved in the tmp dir (temporary doesn't affect python version)
> **zbxtg;channel -- enables sending to channels**

**Comment by ableev** [comment]
Fixed!
