### ISSUE TITLE
Supergroups are not supported

### ISSUE THREAD

**Issue by marckson** [ableev/Zabbix-in-Telegram#32]
After upgrading to supergroup, I can no longer send messages from supergroup to Telegram.
The error is

`zbxtg_group.py: {u'error_code': 400, u'ok': False, u'description': u'[Error]: Bad Request: group chat is migrated to supergroup chat', u'parameters': {u'migrate_to_chat_id': -1001044886132}}`

**Comment by itvdonsk** [comment]
Try delete /tmp/zbxtg/uids.txt

**Comment by ableev** [comment]
@itvdonsk bad tip

**Comment by itvdonsk** [comment]
@ableev Yes, I missed that type of has changed to the "supergroup"

**Comment by itvdonsk** [comment]
@ableev И как я понял это единственное изменение. Просто добавить опцию --supergroup

**Comment by marckson** [comment]
edit and place the correct supergroup ID

user@zabbix:/tmp/zbxtg$ vim uids.txt 
GROUPNAME;group;-1111111111111

**Comment by ableev** [comment]
Fixed long time ago.
