### ISSUE TITLE
Strange fail due to zbxtg;title definition

### ISSUE THREAD

**Issue by SebastianPereiro** [ableev/Zabbix-in-Telegram#4]
Hi!
Thanks for your code!
I have a strange problem with title tag:

sudo -u zabbix ./zbxtg.sh "mishaso" "PROBLEM" "Last value: 38 °C (03:56:48)
> zbxtg;graphs
> zbxtg;graphs_period=10800
> zbxtg;itemid: 23865
> zbxtg;title: Zabbix server - HDD temperature too high"
**{"ok":false,"error_code":400,"description":"Error: IMAGE_PROCESS_FAILED"}**

Same command but with modified title:

sudo -u zabbix ./zbxtg.sh "mishaso" "PROBLEM" "Last value: 38 °C (03:56:48)
> zbxtg;graphs
> zbxtg;graphs_period=10800
> zbxtg;itemid:23865
> zbxtg;title:Zabbix server"
{"ok":true,"result":{"message_id":18,"from":{"id":133785011,"first_name":"Zabbix3a","username":"Zabbix3a_bot"},"chat":{"id":75825145,"first_name":"Misha","last_name":"So","username":"mishaso"},"date":1439641061,"photo":[{"file_id":"AgADAgADsqcxG7Nl-QdEPoTAqQABcOh-6VkqAAQIaMHEsWX9jjY0AQABAg","file_size":748,"width":90,"height":33},{"file_id":"AgADAgADsqcxG7Nl-QdEPoTAqQABcOh-6VkqAATg2st_kQ0mQTU0AQABAg","file_size":9630,"width":320,"height":118},{"file_id":"AgADAgADsqcxG7Nl-QdEPoTAqQABcOh-6VkqAASnvMicpRqE4DQ0AQABAg","file_size":51419,"width":800,"height":296},{"file_id":"AgADAgADsqcxG7Nl-QdEPoTAqQABcOh-6VkqAARNQCIFUZCRmzM0AQABAg","file_size":69879,"width":1016,"height":376}],"caption":"PROBLEM\nLast value: 38 \u00b0C (03:56:48)\n--"}}

How can I help you to fix it?

**Comment by SebastianPereiro** [comment]
Found another error:
sudo -u zabbix ./zbxtg.sh "mishaso" "PROBLEM" "Last value: 25.1 % (17:41:08)
> zbxtg;graphs
> zbxtg;graphs_period=10800
> zbxtg;itemid: 23825
> zbxtg;title: Zabbix server - Disk I/O is overloaded on Zabbix server
> "
{"ok":false,"error_code":400,"description":"Error: **PHOTO_INVALID_DIMENSIONS**"}

**Comment by a-zazell** [comment]
+1, заменил title из примера на
zbxtg;title:{HOST.HOST} - {ITEM.NAME1}

**Comment by ableev** [comment]
@SebastianPereiro you have whitespace after "zbxtg;itemid:", so script didn't get any image from zabbix web ui because of that. Will be fixed in #8. You can checkout branch `issues-8`. Thanks.

@a-zazell не проблема title, как раз, потому что пишет ошибки про фотки.

**Comment by ableev** [comment]
@SebastianPereiro please check python versin
