### ISSUE TITLE
Ability to send part of screen

### ISSUE THREAD

**Issue by sheh1000** [ableev/Zabbix-in-Telegram#40]
Hi,

In [documentation ](https://github.com/ableev/Zabbix-in-Telegram)is described that it is possible to send part of Zabbix screen. How can I do that?

**Comment by ableev** [comment]
Can you show me exact word, please? 
There is no such feature and documentation says that.

**Comment by sheh1000** [comment]
![capture](https://cloud.githubusercontent.com/assets/10128961/15207160/132fe276-1846-11e6-948f-b5d5ab2688d2.PNG)

**Comment by ableev** [comment]
![132fe276-1846-11e6-948f-b5d5ab2688d2](https://cloud.githubusercontent.com/assets/238149/15214466/e5b3d8c4-1855-11e6-8ccb-c0665adf3925.PNG)
