### ISSUE TITLE
Why  I cant get Graphs

### ISSUE THREAD

**Issue by xiaoyawl** [ableev/Zabbix-in-Telegram#43]
[root@iZ626l9a5x1Z /etc/zabbix/script]# python telegram_zabbix.py "@Be***" "Graphs Test" "
zbxtg;graphs
zbxtg;graphs_period=10800
zbxtg;itemid:{24008}" --debug

telegram_zabbix.py: {u'ok': True, u'result': {u'username': u'DT_***', u'first_name': u'Zabbix monitor', u'id': 192***}}
telegram_zabbix.py: Cache file with uids: /tmp/Telegram_zabbix/uids.txt
telegram_zabbix.py: Telegram uid of private 'Be***': 22***

telegram_zabbix.py: Trying to /sendMessage:
telegram_zabbix.py: https://api.telegram.org/***/sendMessage
telegram_zabbix.py: post params: {'text': 'Graphs Test\n\nzbxtg;graphs\nzbxtg;graphs_period=10800\nzbxtg;itemid:{24008}', 'disable_notification': False, 'chat_id': '22***\n', 'disable_web_page_preview': False}

I don't know this is why?

**Comment by ableev** [comment]
@xiaoyawl you log is not full, try to copy and paste everything and use https://telegram.me/ZbxTg for help, it is faster and involves more people. Thanks.

**Comment by xiaoyawl** [comment]
@ableev 
@ZbxTg user not found

**Comment by Savemech** [comment]
@xiaoyawl would you kindly try to copy and paste that name into search box in telegram client, pal?

**Comment by xiaoyawl** [comment]
@ableev 
![1](https://cloud.githubusercontent.com/assets/2193977/16166193/a55fcf48-351b-11e6-9763-988c2007450d.png)

I cant found ZbxTg
