### ISSUE TITLE
Private Channels dont receive messages

### ISSUE THREAD

**Issue by camillagds** [ableev/Zabbix-in-Telegram#44]
My channels are all privates. When I try to send a message to channel I got this error:

`/zbxtg.py "@MyChannel" "teste" "chat oi " --debug --channel
zbxtg.py: {u'ok': True, u'result': {u'username': u'mybot', u'first_name': u'MyBot', u'id': xxxxxxxxxx}}
zbxtg.py: Cache file with uids: /tmp/zbxtg/uids.txt
zbxtg.py: Telegram uid of channel '@MyChannel': @MyChannel
zbxtg.py: Trying to /sendMessage:
zbxtg.py: https://api.telegram.org/botxxxxxx:yyyyyyyyyyyyyyyyyyyyyyyy/sendMessage
zbxtg.py: post params: {'text': 'teste\nchat oi ', 'disable_notification': False, 'chat_id': '@MyChannel', 'disable_web_page_preview': False}
zbxtg.py: {u'error_code': 400, u'ok': False, u'description': u'Bad Request: channel not found'}

But, when i modify to public works.

`

**Comment by ableev** [comment]
There is no way to do it in directly in private channel without some dirty work.
Use this instructions: http://stackoverflow.com/questions/33858927/how-to-obtain-the-chat-id-of-a-private-telegram-channel
