### ISSUE TITLE
Recovery messages are notified as FAIL

### ISSUE THREAD

**Issue by JustDevNull** [ableev/Zabbix-in-Telegram#45]
Every time the recovery message is sended to the group it's labeled as "FAIL" and not as "OK".

The two Zabbix Server versions are 3.0.2 and 3.0.3 and followed the "Working with Zabbix 3.0" at the wiki at the time I added the scripts to the servers.

This is what is received at the Telegram Group once is recovered : 

![image_1](https://cloud.githubusercontent.com/assets/12670733/16375929/2741a77c-3c5e-11e6-8316-daa8eaca37a9.jpg)

The configuration of the action :

![image_2](https://cloud.githubusercontent.com/assets/12670733/16375930/2742f870-3c5e-11e6-87af-de96a963a90e.jpg)

The media of the user :

![image_3](https://cloud.githubusercontent.com/assets/12670733/16375931/274673a6-3c5e-11e6-8110-6d7ebbef5268.jpg)

The media type configuration :

![image_4](https://cloud.githubusercontent.com/assets/12670733/16376079/df29a236-3c5e-11e6-8122-262bb1df37ec.jpg)

**Comment by ableev** [comment]
There is nothing wrong with the script, it's your zabbix action. 
Set your action properly, don't blame notification's method.
Thanks.

**Comment by JustDevNull** [comment]
Thanks for the info and the quick response.

**Comment by ableev** [comment]
Show your action, second tab.

**Comment by JustDevNull** [comment]
Here you have :

![image_5](https://cloud.githubusercontent.com/assets/12670733/16376550/0dd267ba-3c61-11e6-8a0d-c8af9e34f007.jpg)

And it wasn't my intention to blame the script, only opened the issue to obtain some help because I was unable to see why it wasn't working.

**Comment by ableev** [comment]
Add condition "trigger status = problem" and enjoy

**Comment by JustDevNull** [comment]
Lots of thanks, finally shows the "OK".

**Comment by ableev** [comment]
You're welcome
