### ISSUE TITLE
Option to send single message with graph instead of two.

### ISSUE THREAD

**Issue by imraro** [ableev/Zabbix-in-Telegram#47]
Current implementation:
![before](https://cloud.githubusercontent.com/assets/1373816/16678166/53aa5c3e-44fe-11e6-8733-01d9b232bdcf.png)

proposal:
![after](https://cloud.githubusercontent.com/assets/1373816/16678172/61d2c60c-44fe-11e6-9bfe-637389adbfc5.png)

**Comment by ableev** [comment]
It was one message, but you don't understand what it is.
It is not message, it is photo with caption, which is not text. It doesn't support code formatting and so on.

**Comment by imraro** [comment]
>It was one message, but you don't understand what it is.

I understand, but it's still looking like two messages isn't it? )

>It is not message, it is photo with caption, which is not text. It doesn't support code formatting and so on.

Agree, but it can reproduce more solid notification for those who don't need formatting,

P.S.: I'm asking for the option, not for mandatory implementation.
P.P.S: Thank you for good tool, independently of this request!

**Comment by ableev** [comment]
In classic ways of messaging you have attachments.
E-mail has attachments, multiple of them. 
Facebook/VK messages have attachments.
Ticket systems have attachments.

Telegram doesn't have it, it is completely different methods. Even more: captions for photos are clipped to 120 symbols, it is not enough even for default zabbix action.

P.S. Ok, I will make an option for that.
P.P.S. Thank you for feedback. :)

**Comment by imraro** [comment]
Thank you!

>...photos are clipped to 120 symbols...

200 symbols, based on: https://github.com/ableev/Zabbix-in-Telegram/issues/14 ))

**Comment by renatodru** [comment]
it's is possibly with other tool: https://github.com/sansaoipb/Telegram-Graph-authenticated
![telegram](https://cloud.githubusercontent.com/assets/22222527/18560856/c668e2aa-7b53-11e6-927d-bbf4f036b884.png)

**Comment by ableev** [comment]
@renatodru what is this about?

**Comment by Vanav** [comment]
Most annoying in current implementation is that Telegram clients notification always say "Photo", not the text of alert. The other workaround would be to send the photo first, then the alert message?

**Comment by ableev** [comment]
@Vanav in the process of bringing back one message option.

**Comment by Vanav** [comment]
Maybe need a separate issue, but if I use this guide https://github.com/ableev/Zabbix-in-Telegram/wiki/Trigger-severity-as-Emoji and set subject line like this: "[Emoji-Severity] [Time] [PROBLEM/OK] [Description]", then option to edit last message doesn't work, because your code expects subject as "[PROBLEM/OK] [Description]".

**Comment by Varrkan82** [comment]
Confirmed inability to edit messages.

**Comment by ableev** [comment]
@Vanav @Varrkan82 this feature hasn't worked since the first implementation. 
In case you have more then one recipients – it's unable to change previous message.
Plus, there was a lot of strange code for that method.
Will do another way of doing it, but a bit later.
Sorry, guys.
