### ISSUE TITLE
Need file with requirements

### ISSUE THREAD

**Issue by akhodyrev** [ableev/Zabbix-in-Telegram#49]
Need file with requirements because at clean run at new system user can get error like this:

```
user@zabbix:/tmp/alerts/Zabbix-in-Telegram$ ./zbxtg.py
Traceback (most recent call last):
  File "./zbxtg.py", line 8, in <module>
    import requests
ImportError: No module named requests

```

**Comment by glf79** [comment]
I've the same issue.
I've python 2.7 and 3.4.3. I've already installed requests (2.6.0) and requests-oauthlib (0.6.2) but I'm getting always the same issue.

Traceback (most recent call last):
  File "./zbxtg.py", line 8, in <module>
    import requests
ImportError: No module named requests

Can you help me?

**Comment by ableev** [comment]
Added a long time ago.

Speaking of @glf79's problem — probably the versions of python and pip are different.
Anyway, the best way to get help — write to ZbxTg group chat in Telegram.
