### ISSUE TITLE
Error Unicode

### ISSUE THREAD

**Issue by Uzzi** [ableev/Zabbix-in-Telegram#54]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 4751: ordinal not in range(128

Can help me?

**Comment by ableev** [comment]
@Uzzi provide full input/output, I have no idea where did you get it.

**Comment by Uzzi** [comment]
`./zbxtg.py @LenarduzziCgilVe Zabbix ciao da zabbix  --debug
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./zbxtg.py", line 459, in <module>
    main()
  File "./zbxtg.py", line 345, in main
    print_message(tg.get_me())
  File "./zbxtg.py", line 40, in get_me
    me = self.http_get(url)
  File "./zbxtg.py", line 23, in http_get
    answer_json = json.loads(answer.decode('utf8'))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 4751: ordinal not in range(128)
`

**Comment by ableev** [comment]
@Uzzi I suggest you to join group chat https://telegram.me/ZbxTg and discuss your problems there. 
Probably you have old version(s) of python / requests.
