### ISSUE TITLE
{u'error_code': 400, u'ok': False, u'description': u'PHOTO_INVALID_DIMENSIONS'}

### ISSUE THREAD

**Issue by gelato** [ableev/Zabbix-in-Telegram#57]
I'm performing check from the manual:
./zbxtg_group.py "my group" test "$(echo -e 'zbxtg;graphs: \nzbxtg;graphs_period=600\nzbxtg;itemid:22181\nzbxtg;title:ololo')"
and in returns 
{u'error_code': 400, u'ok': False, u'description': u'PHOTO_INVALID_DIMENSIONS'}
while url is correct:
curl -sI http://127.0.0.1/zabbix/chart3.php | head -1
HTTP/1.1 200 OK

Zabbix shows that bot readonly user is online.

What is wrong?

**Comment by ableev** [comment]
@gelato what's in config file?

**Comment by gelato** [comment]
# -*- coding: utf-8 -*-

tg_key = "api###"  # telegram bot api key

zbx_tg_prefix = "zbxtg"  # variable for separating text from script info
zbx_tg_tmp_dir = "/tmp/" + zbx_tg_prefix  # directory for saving caches, uids, cookies, etc.
zbx_tg_signature = False

zbx_server = "http://127.0.0.1/zabbix"  # zabbix server full url
zbx_api_user = "watchdog"
zbx_api_pass = "Mast*rOf0Z"
zbx_api_verify = True  # True - do not ignore self signed certificates, False - ignore

proxy_to_zbx = None
proxy_to_tg = None

#proxy_to_zbx = "proxy.local:3128"
#proxy_to_tg = "proxy.local:3128"

emoji_map = {
    "ok": " ",
    "problem": " ",
    "info": "ℹ️",
    "warning": "⚠️",
    "disaster": " ",
    "bomb": " ",
    "fire": " ",
    "hankey": " ",
}


With debug:

zbxtg.py: http://127.0.0.1/zabbix/chart3.php?period=600&name=ololo&width=900&height=200&graphtype=0&legend=1&items[0][itemid]=22181&items[0][sortorder]=0&items[0][drawtype]=5&items[0][color]=00CC00
zbxtg.py: Trying to /sendMessage:
zbxtg.py: https://api.telegram.org/api###/sendMessage
zbxtg.py: post params: {'text': 'test', 'disable_notification': False, 'chat_id': '-163843980\n', 'disable_web_page_preview': False}
zbxtg.py: Trying to /sendPhoto:
zbxtg.py: https://api.telegram.org/api###/sendPhoto
zbxtg.py: {'caption': '', 'disable_notification': True, 'chat_id': '-163843980\n', 'reply_to_message_id': 19}
zbxtg.py: files: {'photo': <open file '/tmp/zbxtg/22181.png', mode 'rb' at 0x27d4300>}
zbxtg.py: {u'error_code': 400, u'ok': False, u'description': u'PHOTO_INVALID_DIMENSIONS'}

[root@Zabbix server alertscripts]# cat /tmp/zbxtg/22181.png

cat: /tmp/zbxtg/22181.png: No such file

But i can see graph on url: http://127.0.0.1/zabbix/chart3.php?period=600&name=ololo&width=900&height=200&graphtype=0&legend=1&items[0][itemid]=22181&items[0][sortorder]=0&items[0][drawtype]=5&items[0][color]=00CC00

/tmp/zbxtg is writable - it already has uids.txt

**Comment by gelato** [comment]
Fixed by myself. Just needed to grant all readonly permissions to zabbix user, while first time i gave only to some hostgroups. Sorry.
