### ISSUE TITLE
can't get chat_id properly

### ISSUE THREAD

**Issue by ekbfh** [ableev/Zabbix-in-Telegram#6]
Hi!
My bot refuses to get chat_id, so i look at code and make a workaround by changing 
MATCH=".chat.:{.id.:.*,.username.:.${TO}.}"
to
MATCH="{.id.:.*,.username.:.${TO}.}"

Now it works for me.
Maybe you should rewrite it more clearly, but it works.

**Comment by ableev** [comment]
Thank you, @ekbfh.
Yes, this is because of non-optimal `grep`. Already fixed in #8, you can checkout `issues-8` branch.
