### ISSUE TITLE
Login to Zabbix web UI has failed

### ISSUE THREAD

**Issue by wmbzz** [ableev/Zabbix-in-Telegram#60]
Hey guys!

I'm setting this software in my Zabbix enviroment. I've managed to send a message manually, but when using it inside Zabbix I receive this error:

```
zbxtg.py: authorization has failed, url: http://x.x.x.x/
zbxtg.py: Login to Zabbix web UI has failed, check manually...
```

I've redacted the URL of my server. I use LDAP authentication on Zabbix, and I've already tested the password and it works fine (I also have Grafana which connects to my Zabbix just fine). Does this works with LDAP authentication, or is something else wrong? This are my settings:

```
# -*- coding: utf-8 -*-

tg_key = "REDACTED"  # telegram bot api key

zbx_tg_prefix = "zbxtg"  # variable for separating text from script info
zbx_tg_tmp_dir = "/tmp/" + zbx_tg_prefix  # directory for saving caches, uids, cookies, etc.
zbx_tg_signature = False

zbx_server = "http://redacted"  # zabbix server full url
zbx_api_user = "redacted"
zbx_api_pass = "redacted"
zbx_api_verify = True # True - do not ignore self signed certificates, False - ignore

proxy_to_zbx = None
proxy_to_tg = None

#proxy_to_zbx = "proxy.local:3128"
#proxy_to_tg = "proxy.local:3128"

emoji_map = {
    "ok": "✅",
    "problem": "❗",
    "info": "ℹ️",
    "warning": "⚠️",
    "disaster": "❌",
    "bomb": "💣",
    "fire": "🔥",
    "hankey": "💩",
}
```

I've also changed `zbx_api_verify` from true to false, and tried using other user. This is a message I just sent myself manually using zbxtg.py:

![sem titulo](https://cloud.githubusercontent.com/assets/6979278/19986355/7a81997e-a1fd-11e6-86b6-28c80102228e.png)

**Comment by thiagoescobar** [comment]
i had the same problem, in my case the zbx_server url was not set properly. i changed it to http://myserverip/zabbix and then it worked.

**Comment by wmbzz** [comment]
@thiagoescobar OK, feeling really stupid right now. It's working now, thank you so much!
