### ISSUE TITLE
Test ./zbxtg.py fail

### ISSUE THREAD

**Issue by gcolomb** [ableev/Zabbix-in-Telegram#61]
Hi, 'ive followed all steps, also create telegram bot, but result is this:

root@ubuntu:/usr/lib/zabbix/alertscripts# ./zbxtg.py "@ZabbizAlertsBot" TEST TEST --debug
zbxtg.py: {u'ok': True, u'result': {u'username': u'ZabbizAlertsBot', u'first_name': u'ZabbixAlert', u'id': 260571066}}
zbxtg.py: Cache file with uids: /tmp/zbxtg/uids.txt
zbxtg.py: Getting uid from /getUpdates...
zbxtg.py: https://api.telegram.org/bot260571066:AAE0godskTblvuIk_quHTzyYDb3WffPrHgM/getUpdates
zbxtg.py: Content of /getUpdates:
zbxtg.py: {u'ok': True, u'result': []}
zbxtg.py: User 'ZabbizAlertsBot' needs to send some text bot in private

Thanks for help
Gianluca

**Comment by ableev** [comment]
@gcolomb the first argument is your username, not bot's

**Comment by gcolomb** [comment]
Thank you for answer. Now if I try to send a test message with manual command, it works:

/zbxtg.py "Zabbix notification" test test
"Zabbix notification" is a group i've created for tests.

But in zabbix, when i simulate alert, i see in dashboard that the message is sent, but i ndon't receive it.
<img width="475" alt="immagine" src="https://cloud.githubusercontent.com/assets/23638945/20527721/ba0c469a-b0c9-11e6-86e8-9cc3317e9694.png">

**Comment by gcolomb** [comment]
Now it works. I've modified configuration in zabbix. Thank You for support

**Comment by ableev** [comment]
@gcolomb you're welcome
