### ISSUE TITLE
Messages are not sent

### ISSUE THREAD

**Issue by thiagoescobar** [ableev/Zabbix-in-Telegram#62]
For some reason, the bot doesnt send the messages. 

The action is created when trigger occurs and the message is sent when i test it on the console, but is not sent when the action is created (even though it is label as Sent in zabbix action log). 

I tried debugging with --debug , but nothing gets written on server log. 

Please help!

**Comment by lbr88** [comment]
Make sure the zabbix user has permissions to the /tmp folder that it 
creates (defined in the config) if you tested this as root in the console 
it might have the wrong permissions. (root instead of zabbix depending on 
your system)

**Comment by thiagoescobar** [comment]
I just tried running the script on shell with the zabbix user and it works perfectly, but the action still doesnt send the message

**Comment by lbr88** [comment]
does the zabbix web interface indicate that the action has failed or succeeded?

**Comment by thiagoescobar** [comment]
wrong configuration on zbxtg_settings.py . just solved
