### ISSUE TITLE
can't send graphs

### ISSUE THREAD

**Issue by sorin2343** [ableev/Zabbix-in-Telegram#63]
hi , 
I use zabbix 3.2.1 and my alert look like this :
Last value: {ITEM.LASTVALUE1} ({TIME})
zbxtg;graphs
zbxtg;graphs_period=10800
zbxtg;itemid:{ITEM.ID1}
zbxtg;title:{HOST.HOST} - {TRIGGER.NAME} .

With this settings I don't get the graph image in message .

How can I test debug ?

**Comment by ableev** [comment]
@sorin2343 please, see wiki pages to get help

**Comment by derdeagle** [comment]
Have you checked the following:

- Password valid (correct, not expired, ...)
- The URI in the settings is correct
- --debug Any errors?

**Comment by sorin2343** [comment]
password is valid and tested in web client .
debug is not working .

**Comment by lbr88** [comment]
Try looking at your webserver log to see if the request is denied.

**Comment by sorin2343** [comment]
how ?

**Comment by sorin2343** [comment]
look at one of my message :
Zabbix Win BOT, [05.12.16 16:10]
FAIL: cpu to high on Laptop ISP
zbxtg;graphs
zbxtg;graphs_period=10800
zbxtg;graphs_width=700
zbxtg;graphs_height=300
zbxtg;itemid:26215
zbxtg;title:Laptop ISP - cpu to high
zbxtg;debug

**Comment by sorin2343** [comment]
I tried to use another zabbix api , like https://github.com/blacked/py-zabbix .
I seems to work the examples is the first page

**Comment by ableev** [comment]
@sorin2343 https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-test-script-in-command-line

"debug is not working" – there is no information in your messages, they are useless. 

Read manuals in the wiki, it was in the first comment, you ignored it.

**Comment by sorin2343** [comment]
[root@win-zbx1 alertscripts]# curl -sI http://win-zbx.emag.network/chart3.php | head -1
HTTP/1.1 200 OK
and 
./zbxtg.py SorinIspas test "$(echo -e 'zbxtg;graphs: \nzbxtg;graphs_period=3600\nzbxtg;itemid:26215\nzbxtg;title:ololo')"
I got message 
test
zbxtg;graphs: 
zbxtg;graphs_period=3600
zbxtg;itemid:26215
zbxtg;title:ololo

**Comment by ableev** [comment]
@sorin2343 show me your config.

**Comment by sorin2343** [comment]
[root@win-zbx1 alertscripts]# cat zbxtg_settings.py
# -*- coding: utf-8 -*-

tg_key = "313716114:AAFcg0dhwnqiaFCNbHtjArnmWEQ1JF1l-Cs"  # telegram bot api key

zbx_tg_prefix = "WIN"  # variable for separating text from script info
zbx_tg_tmp_dir = "/tmp/" + zbx_tg_prefix  # directory for saving caches, uids, cookies, etc.
zbx_tg_signature = False

zbx_server = "http://win-zbx.emag.network"  # zabbix server full url
zbx_api_user = "win.bot"
zbx_api_pass = "****"
zbx_api_verify = False  # True - do not ignore self signed certificates, False - ignore

proxy_to_zbx = None
proxy_to_tg = None

#proxy_to_zbx = "proxy.local:3128"
#proxy_to_tg = "proxy.local:3128"

emoji_map = {
    "ok": "✅",
    "problem": "❗",
    "info": "ℹ️",
    "warning": "⚠️",
    "disaster": "❌",
    "bomb": "💣",
    "fire": "🔥",
    "hankey": "💩",
}

**Comment by ableev** [comment]
@sorin2343 can you explain why have you changed `zbx_tg_prefix` variable?

**Comment by sorin2343** [comment]
no reason , business purpose.
should not be changed  ?

**Comment by ableev** [comment]
@sorin2343 and how this variable is helping your business?

**Comment by sorin2343** [comment]
changed back to zgxtg and it's working

**Comment by sorin2343** [comment]
thanks
