### ISSUE TITLE
Graphs in Zabbix 3.2

### ISSUE THREAD

**Issue by kykykaka** [ableev/Zabbix-in-Telegram#67]
Hi!
May be it can help to smb.
If you are using Zabbix 3.2, you should change the zbx_img_ulr var to:

`zbx_img_url = self.server + "/chart.php?period={1}&itemids[0]={0}&width={2}&height={3}".format(itemid, period, width, height)`

**Comment by ableev** [comment]
Probably, should be fixed in script. 
I'll think about it.

**Comment by kykykaka** [comment]
I've done thoroughly research and realized that i was wrong. Sorry. Everything is ok with your link in 3.2 too.

**Comment by ableev** [comment]
I see, thanks then
