### ISSUE TITLE
Не отправляется график 

### ISSUE THREAD

**Issue by OSidorenkov** [ableev/Zabbix-in-Telegram#7]
Сделал все по статье, отправляется текст оповещалки, а график не хочет. При этом в логе заббикс сервера:
/var/lib/zabbixsrv/alertscripts/zbxtg.sh: line 20: /tmp/zbxtg/graph..png: Отказано в доступе
rm: невозможно удалить «/tmp/zbxtg/graph..png»: Нет такого файла или каталога
Между точками исходя из скрипта должен находится item_id, но его нет. 
Версия заббикс сервера 2.2.10
Запустить скрипт для получения графика в ручную пытался, получаю:
![photo_2015-12-08_18-20-44](https://cloud.githubusercontent.com/assets/12871885/11659279/7adcf6ea-9dd8-11e5-91e0-2d56a0cecbf7.jpg)
Можете пояснить, может что не так делаю?

**Comment by OSidorenkov** [comment]
Возможно в этом дело:
<img data-timestamp="1449593104338" id="historyGraph" src="chart.php?itemid=25786&amp;period=3600&amp;stime=20161207184435&amp;updateProfile=1&amp;profileIdx=web.item.graph&amp;profileIdx2=25786&amp;sid=117306e72450bc74&amp;width=1222&amp;curtime=1449593104338" style="position: relative; z-index: 2;">

Выше написал код элемента, а точнее сам график отрисованный на основе триггера. Я думаю, что запрос здесь и в скрипте отличается, можете помочь написать на основе этого правильный запрос?

**Comment by ableev** [comment]
@OSidorenkov напишите в телеграм, пожалуйста, быстрее будет, думаю. Такой же, как и профиль здесь.

**Comment by ableev** [comment]
Проблема была в том, что после "itemid:" и "title:" были пробелы. Нашли, починили.
Уберу `grep -P` из кода, ибо слишком жёсткие правила приходится соблюдать. 
#8 и ветка `issues-8` помогут.
