### ISSUE TITLE
External images to telegram

### ISSUE THREAD

**Issue by ableev** [ableev/Zabbix-in-Telegram#71]
It would be great if we can attach images from external sources (i.e. Grafana).

**Comment by Smiley-k** [comment]
Yes, good idea

**Comment by ableev** [comment]
Test:
```python zbxtg.py ableev test1 "$(echo -e 'test2\nzbxtg;zbxtg;external_image:https://www.zabbix.com/img/zabbix_logo.png\nzbxtg;graphs')"```

**Comment by ableev** [comment]
Just realized that this feature doesn't work with python 3
