### ISSUE TITLE
Can't get graph image

### ISSUE THREAD

**Issue by Okil** [ableev/Zabbix-in-Telegram#72]
Description of the warning to come, but graphs no

**Comment by ableev** [comment]
@Okil and how am I suppose to know what are you trying to do?

**Comment by Okil** [comment]
![image](https://cloud.githubusercontent.com/assets/18390620/26491347/b426fdec-4228-11e7-95f7-f5bc915dce69.png)

**Comment by ableev** [comment]
It is not the answer for "what are you trying to do".
@Okil , everything is working on my zabbix. See wiki / README for details.

**Comment by ableev** [comment]
@Okil , so, will you share any input / output? Or it can be closed as invalid issue?
