### ISSUE TITLE
Not all emoji working \ Zabbix database error

### ISSUE THREAD

**Issue by Zaurrex** [ableev/Zabbix-in-Telegram#73]
Hi!
First of all
Thank you a lot for the bot !)

I found out, that the  Zabbix Action forms work with emoji only if they have 6-digit UTF-8 hex code.
Any of them, not only mentioned in the config file
When I'm trying to add some 8-digit emoji it results in a database error:
`[Incorrect string value: '\xF0\x9F\x8F\xA2\x0D\x0A...' for column 'def_longdata' at row 1]`

I have updated the database to utf8mb4_unicode_ci, and now I can add 8-digit emoji directly to the MYSQL base without such error.

But the Zabbix web server and the bot still are showing "?" instead of them.

Does the emoji in the config file helps to skip this error?

UPD. Have just read the emoji wiki... will try to add 8digit emoji to the map in the config.

**Comment by ableev** [comment]
I think that we (users) shouldn't change database / frontend by ourself – zabbix team releases updates regularly.
For Emoji lovers – there is emoji map.
