### ISSUE TITLE
 how to solve :{u'error_code': 409, u'ok': False, u'description': u"Conflict: can't use getUpdates method while webhook is active"} 

### ISSUE THREAD

**Issue by sesepehr** [ableev/Zabbix-in-Telegram#76]
{u'error_code': 409, u'ok': False, u'description': u"Conflict: can't use getUpdates method while webhook is active"}
please help me

**Comment by ableev** [comment]
Hi, my name is Captain Obvious and here I am to help...
@sesepehr you can't use both methods webhook and getUpdates.
If you wan't to use that bot, you should turn off webhook.
Easy way – is to delete you bot and request new one from BotFather.

**Comment by sesepehr** [comment]
thanks for help ,it solved
