### ISSUE TITLE
Send graph only if it exists

### ISSUE THREAD

**Issue by mmoryakov** [ableev/Zabbix-in-Telegram#78]
Hello,
I have make the trigger on item which gather an errors appeared on log file and there is no graph for this item . So script sending the graph with no data.
Is it possible  to check if there is the graph to send and do not send if graph absent?

**Comment by ableev** [comment]
What do you mean by "exist"? 

If it's log item, you can't show values on graph, so you don't need to create an action with graph.

More things to do if we are going to check item's type.

Now: action triggered -> script runs -> downloads graph (back in zabbix) -> saves graph to disk (io) -> sends graph to user (external connection to telegram).

After: action triggered -> script runs -> check item's type (back in zabbix) -> download graph if it's numeric -> ...

The process is already not so fast, and you are suggesting to slow it down.

**Comment by Realmagnum** [comment]
In my not big installation i dont want to receive blank graph from string type item.
Can you make an option to exclude non numeric graphs?
Tnx.

**Comment by ableev** [comment]
@Realmagnum there is: do not create action which covers all triggers.
Read previous comment from me.
You are suggesting me to change code so it will check zabbix api every time, I don't want to do it.

**Comment by ableev** [comment]
When Zabbix implement proper API to communicate with third-party software such as alert scripts, I'll do it.
