### ISSUE TITLE
what mean this error

### ISSUE THREAD

**Issue by sirdrug** [ableev/Zabbix-in-Telegram#84]
18718:20170914:123233.936 query [txnlev:1] [update alerts set status=2,retries=3,error='zbxtg.py: {u''ok'': True, u''result'': {u''username'': u''Desnol_Alarm_bot'', u''first_name'': u''Desnol_Alarm_bot'', u''is_bot'': True, u''id'': 397911741}}

**Comment by sirdrug** [comment]
in console everything allright

**Comment by ableev** [comment]
@sirdrug provide a bit more logs please

**Comment by sirdrug** [comment]
18718:20170914:135924.009 query [txnlev:1] [update alerts set status=0,retries=2,error='zbxtg.py: {u''ok'': True, u''result'': {u''username'': u''Desnol_Alarm_bot'', u''first_name'': u''Desnol_Alarm_bot'', u''is_bot'': True, u''id'': 397911741}}
zbxtg.py: Cache file with uids: /tmp/zbxtg/uids.txt
zbxtg.py: Getting uid from /getUpdates...
zbxtg.py: https://api.telegram.org/bot397911741:AAFjCHesZIocMuHPKOcG3Lv02EcBf9FSsnE/getUpdates
zbxtg.py: Content of /getUpdates:
zbxtg.py: {u''ok'': True, u''result'': [{u''message'': {u''from'': {u''username'': u''sirdrug'', u''first_name'': u''\u0414\u043c\u0438\u0442\u0440\u0438\u0439'', u''last_name'': u''\u042f\u043a\u043e\u0432\u043b\u0435\u0432'', u''is_bot'': False, u''language_code'': u''ru-RU'', u''id'': 252952539}, u''text'': u''/start'', u''entities'': [{u''length'': 6, u''type'': u''bot_command'', u''offset'': 0}], u''chat'': {u''username'': u''sirdrug'', u''first_name'': u''\u0414\u043c\u0438\u0442\u0440\u0438\u0439'', u''last_name'': u''\u042f\u043a\u043e\u0432\u043b\u0435\u0432'', u''type'': u''private'', u''id'': 252952539}, u''date'': 1505311948, u''message_id'': 9}, u''update_id'': 95197276}, {u''message'': {u''from'': {u''username'': u''static302'', u''first_name'': u''Kirill'', u''last_name'': u''Ilyashenko'', u''is_bot'': False, u''id'': 192447194}, u''text'': u''/start'', u''entities'': [{u''length'': 6, u''type'': u''bot_command'', u''offset'': 0}], u''chat'': {u''username'': u''static302'', u''first_name'': u''Kirill'', u''last_name'': u''Ilyashenko'', u''type'': u''private'', u''id'': 192447194}, u''date'': 1505312138, u''message_id'': 11}, u''update_id'': 95197277}, {u''message'': {u''date'': 1505312141, u''text'': u''sdjkfh'', u''from'': {u''username'': u''static302'', u''first_name'': u''Kirill'', u''last_name'': u''Ilyashenko'', u''is_bot'': False, u''language_code'': u''ru-RU'', u''id'': 192447194}, u''message_id'': 12, u''chat'': {u''username'': u''static302'', u''first_name'': u''Kirill'', u''last_name'': u''Ilyashenko'', u''type'': u''private'', u''id'': 192447194}}, u''update_id'': 95197278}, {u''update_id'': 95197279, u''channel_post'': {u''date'': 1505314466, u''new_chat_photo'': [{u''width'': 160, u''height'': 160, u''file_id'': u''AgADAgADBKgxG9u_Ew91gg2XzuxQpxPNDw4ABInraGh3AwkheI4AAgI'', u''file_size'': 10371}, {u''width'': 320, u''height'':' where alertid=94;

**Comment by sirdrug** [comment]
Don't send message in group chat, personal delivery work fine

**Comment by itjwd-works** [comment]
Hi sirdrug, 

what is the fix to send message in private? 
I'm still getting this error 

> zbxtg.py: User 'userName' needs to send some text bot in private

**Comment by mbuyukkarakas** [comment]
Same problem. How to solve this ? 
"zbxtg.py: User 'userName' needs to send some text bot in private"

**Comment by ableev** [comment]
Every problem described above is a consequence of not reading the README and Wiki.
