### ISSUE TITLE
Graphs and Zabbix 3

### ISSUE THREAD

**Issue by stalsbyt** [ableev/Zabbix-in-Telegram#86]
Hello. Graph not work with Zabbix 3.
When I add "zbxtg;graph" to action - notifications not work. Without it - will work fine!

**Comment by ableev** [comment]
@stalsbyt 
1. try dev branch
2. use wiki
3. you didn't provide any helpful info, I can't guess what are you doing.
4. There is a ZbxTg chat in Telegram
