### ISSUE TITLE
Feature request. Add an "Acknowledged" button to add an acknowledge message to an issue in the Zabbix.

### ISSUE THREAD

**Issue by Varrkan82** [ableev/Zabbix-in-Telegram#87]
Hi Ilya.
Is it hard to add an "Acknowledged" (or a something like this) button to an alert message which will be add an Acknowledge message (some default message or inputted by user) to an issue in the Zabbix? 
Maybe only for an alerts with a selected severities. And if it possible - to add a username who pressed a button.
Thanks.

**Comment by ableev** [comment]
@Varrkan82 
Hi. 
You can add link to acknowledge window using markdown or html. 
There is a little project of interactive bot, see #53, so it can be done with this.
But it is not safe to make changes to database via telegram bot, I'm afraid it's too risky to implement.

**Comment by Varrkan82** [comment]
> But it is not safe to make changes to database via telegram bot, I'm afraid it's too risky to implement.
And what about an API request from a localhost?

**Comment by ableev** [comment]
And what if someone compromised your telegram account? 
Or, you gave right to acknowledge something and that guy get fired long time after, who will be responsible if he does something via bot?

**Comment by Varrkan82** [comment]
> And what if someone compromised your telegram account?

It is possible and a bit risky. But it could be implemented "without warranties" from your side as a developer. For our own risk as for a users of your script.

> Or, you gave right to acknowledge something and that guy get fired long time after, who will be responsible if he does something via bot?

This guy will banned in Zabbix and in a TG channel (same about an emails, dev. repositories, etc.). If no - this will mean that we do our work bad (as admins responsible for a security and accounts closing).

**Comment by Varrkan82** [comment]
We can restrict the DB user to update only a selected columns in a tables "acknowledges" and "events" for a security reasons.
Please, can you implement this feature? Thanks.

**Comment by ableev** [comment]
@Varrkan82 if you want it "right now", probably, I won't do it in one week or even month.
1. Too busy
2. Want to do something else with the script, e.g. fix errors or something. 
So for me it is minor-minor priority, sorry.

**Comment by Varrkan82** [comment]
@ableev no any urgency for now. My own request only. It will be perfect if it would be implemented at all. Thanks.

**Comment by AlexGluck** [comment]
+1

**Comment by ableev** [comment]
I always say that the script should be safe for a non-experienced user. 
It should not harm in any way, especially if it is running inside some serious infrastructure.

But you can create an action with a quick URL to acknowledge an event.

Action example:

```
{{{TRIGGER.SEVERITY}}}{TRIGGER.NAME} on {HOSTNAME}
```
```
Last value: {ITEM.LASTVALUE1} ({TIME})
Started: {EVENT.TIME} {EVENT.DATE}
You can [acknowledge](http://192.168.56.102/zabbix/zabbix.php?action=acknowledge.edit&backurl=zabbix.php%3Faction%3Dproblem.view%26page%3D1%26uncheck%3D1&eventids%5B0%5D={EVENT.ID}) this event
zbxtg;markdown
zbxtg;graphs
zbxtg;graphs_period=10800
zbxtg;itemid:{ITEM.ID1}
zbxtg;title:{HOST.HOST} - {TRIGGER.NAME}
```

How it looks like:
![image](https://user-images.githubusercontent.com/238149/54483569-4c91d300-4866-11e9-856f-e862214332b0.png)
![image](https://user-images.githubusercontent.com/238149/54483571-51ef1d80-4866-11e9-8a48-83d596f3240f.png)

Pros:
1. You can quickly acknowledge
2. It is safe, you should be logged in
3. A bot cannot hurt your monitoring system

Cons:
1. You should be logged in, but it is safe
2. You need to open a browser

**Comment by ableev** [comment]
https://github.com/ableev/Zabbix-in-Telegram/wiki/Acknowledge-an-event-using-the-script
