### ISSUE TITLE
Can i customize the timer messages and other things

### ISSUE THREAD

**Issue by Dav1XD** [ableev/Zabbix-in-Telegram#88]
Hi !

I have a doubt. Can i costumize the timer sender to telegram. I mean, i don't wanna messages all the time. I wanna that advise me when something going wrong, but with interval each of message. 
And i wanna know if it's possible to send me message only to events that have high priority like "high" or "disaster"

Forgive me for my horrible english and thanks ;)

**Comment by ableev** [comment]
I don't understand what you mean by "customise timer". Could you please be more specific?

And yes, it is possible to send only high and disaster, configure your actions, there is info how to do it in the official documentation.

**Comment by Dav1XD** [comment]
example, my server stopped working. So the telegram will send me a message. I want an interval for this messages. I tested other application and I have sent me every minute and I do not wanna that

**Comment by ableev** [comment]
You can set interval and escalation steps, check Zabbix documentation
