### ISSUE TITLE
Не отсылаются часть проблем в Telegram

### ISSUE THREAD

**Issue by OSidorenkov** [ableev/Zabbix-in-Telegram#9]
И снова, здравствуйте! На сей раз столкнулся с необычной проблемой. Суть проблемы заключается в том, что при срабатывании триггеров, часть проблем в ТГ не отправляется, хотя сам мониторинг утверждает, что он отправлял все проблемы.
Попробую продемонстрировать наглядно:
![ae4cc0d897](https://cloud.githubusercontent.com/assets/12871885/11836453/ed8fb2cc-a3eb-11e5-91a4-f44f817d2953.png)
Могу с уверенностью, сказать что в действии было указано и выполнено - все проблемы отправлять пользаку с ботом телеграмма.
В итоге получаю 1 нотифай о проблеме:
![12312](https://cloud.githubusercontent.com/assets/12871885/11836616/eb3fc40c-a3ec-11e5-9547-9b6ec0f483e6.png)
(Остальные где-то потерялись)
Зато после восстановления, получил ОК по всему))):
![1231231](https://cloud.githubusercontent.com/assets/12871885/11836690/5f576fac-a3ed-11e5-86de-4b58465e7ac1.png)
Исходя из политики безопасности, я закрасил адреса и названия хостов.
Могу сказать, что триггеры в основном нацелены на проверку процессов сервиса и прослушивания портов.

**Comment by ableev** [comment]
That happens because of limitation for media caption.
If you will try to send caption (message with photo), you will get the error "MEDIA_CAPTION_TOO_LONG" if caption's length is more than 178 symbols.

**Comment by ableev** [comment]
<img width="408" alt="screenshot 2015-12-23 20 51 02" src="https://cloud.githubusercontent.com/assets/238149/11981836/478bbffc-a9b7-11e5-98bf-b92857411084.png">

All messages bigger than 200 symbols will be truncated, you will see the warning in zabbix_server.log

**Comment by ableev** [comment]
@OSidorenkov tested on unreal conditions :) so it must work in your cases
