### ISSUE TITLE
Problem with graph with let's encrypt ssl certificate

### ISSUE THREAD

**Issue by matteokutufa** [ableev/Zabbix-in-Telegram#90]
I found a problem sending graphs when I use let's encrypt ssl certificate
I solved using:

res = requests.get(zbx_img_url, cookies=self.cookie, proxies=self.proxies, verify=False)

instead of:

res = requests.get(zbx_img_url, cookies=self.cookie, proxies=self.proxies, verify=self.verify)

around line 191 in zbxtg.py

**Comment by ableev** [comment]
1. You are not showing any problems here, how could I guess which problem should be fixed?
2. It is not correct, and it is not a workaround, you need to change that option in settings file

**Comment by ableev** [comment]
I tested it on letsencrypt cert, works fine
