### ISSUE TITLE
Not work on zabbix 3.4

### ISSUE THREAD

**Issue by OpneMind** [ableev/Zabbix-in-Telegram#91]
Hi
Zabbix-in-Telegram not working on zabbix 3.4.
how to solve this problem?

**Comment by OpneMind** [comment]
solved

**Comment by esnet75** [comment]
Hi OpneMind how you resolve it?
Every time I've try to test by command line i get "needs to send some text bot in private"
I've zabbix 3.4.3 just installed

**Comment by ableev** [comment]
@esnet75 check wiki, it will help you
