### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by alphaonex86** [ableev/Zabbix-in-Telegram#96]
Hi,
was worked, but not now, I change nothing:

zbxtg_group.py: {u'ok': True, u'result': {u'username': u'zabbixXXXXX_bot', u'first_name': u'zabbixXXXX', u'is_bot': True, u'id': 461468424}}
zbxtg_group.py: Cache file with uids: /tmp/zbxtg/uids.txt
zbxtg_group.py: Getting uid from /getUpdates...
zbxtg_group.py: https://api.telegram.org/XXXXXXXXXXXXX/getUpdates
zbxtg_group.py: Content of /getUpdates:
zbxtg_group.py: {u'ok': True, u'result': [{u'message': {u'date': 1508976488, u'text': u'hhh', u'from': {u'username': u'alpha_one_x86', u'first_name': u'Herman', u'last_name': u'Brule', u'is_bot': False, u'language_code': u'en-US', u'id': 137156893}, u'message_id': 17, u'chat': {u'username': u'alpha_one_x86', u'first_name': u'Herman', u'last_name': u'Brule', u'type': u'private', u'id': 137156893}}, u'update_id': 200568280}, {u'message': {u'from': {u'username': u'alpha_one_x86', u'first_name': u'Herman', u'last_name': u'Brule', u'is_bot': False, u'language_code': u'en-US', u'id': 137156893}, u'text': u'/start', u'entities': [{u'length': 6, u'type': u'bot_command', u'offset': 0}], u'chat': {u'username': u'alpha_one_x86', u'first_name': u'Herman', u'last_name': u'Brule', u'type': u'private', u'id': 137156893}, u'date': 1508976504, u'message_id': 18}, u'update_id': 200568281}, {u'message': {u'from': {u'username': u'alpha_one_x86', u'first_name': u'Herman', u'last_name': u'Brule', u'is_bot': False, u'language_code': u'en-US', u'id': 137156893}, u'text': u'/stop', u'entities': [{u'length': 5, u'type': u'bot_command', u'offset': 0}], u'chat': {u'username': u'alpha_one_x86', u'first_name': u'Herman', u'last_name': u'Brule', u'type': u'private', u'id': 137156893}, u'date': 1508976647, u'message_id': 19}, u'update_id': 200568282}, {u'message': {u'from': {u'username': u'alpha_one_x86', u'first_name': u'Herman', u'last_name': u'Brule', u'is_bot': False, u'language_code': u'en-US', u'id': 137156893}, u'text': u'/start', u'entities': [{u'length': 6, u'type': u'bot_command', u'offset': 0}], u'chat': {u'username': u'alpha_one_x86', u'first_name': u'Herman', u'last_name': u'Brule', u'type': u'private', u'id': 137156893}, u'date': 1508976650, u'message_id': 20}, u'update_id': 200568283}]}
zbxtg_group.py: You need to mention your bot in 'XXXX zabbix' group chat (i.e. type @YourBot)

Cheers,

**Comment by Varrkan82** [comment]
Change your temporary folder from in config file from default **/tmp/zbxtg** to something else. Mention your bot again. This happened after canno your server reboot I suggest..?

**Comment by alphaonex86** [comment]
Same, I have test with empty folder

**Comment by Varrkan82** [comment]
This why you need to mention your bot again. There is no uids.txt file, that created after mentioning a bot.

**Comment by alphaonex86** [comment]
Same, I have mentioned again my bot. no uids.txt file created

**Comment by Varrkan82** [comment]
To mention your bot type '/start@YourBotName' in a channel/private/group

**Comment by alphaonex86** [comment]
Into the group I have write:
/start@mebotname
/start @mebotname
/start@mebotname_bot
/start @mebotname_bot
@mebotname_bot
Hi @mebotname_bot
Of course I have replaced mebotname_bot by the real name

**Comment by Varrkan82** [comment]
If file not created - drop your bot from a channel and invite him back and mention him again. And don't use zbxtg_group.py script! Use `zbxtg.py YourBotName test test --group` for test.

**Comment by ableev** [comment]
Updated wiki page: https://github.com/ableev/Zabbix-in-Telegram/wiki/How-to-send-message-to-the-group-chat
Thanks everyone for feedback.
