### ISSUE TITLE
Feature request : able to use more than one TG Bot for different groups

### ISSUE THREAD

**Issue by jvgenderen** [ableev/Zabbix-in-Telegram#98]
i would like to send triggers to different TG bots from the different user(groups).

eg : usergroup :**team1** uses **team1_bot** and **team2** uses **team2_bot** both are a part of two different TG groups.

**Comment by ableev** [comment]
Now you can use "--tg-key" outside the config file with the key itself right after that option.

1. Create the first bot (add "--group" if you're using group):
![image](https://user-images.githubusercontent.com/238149/54482738-506b2880-4859-11e9-8ca3-e461a09c047b.png)
2. Create the second bot (add "--group" if you're using group):
![image](https://user-images.githubusercontent.com/238149/54482741-5b25bd80-4859-11e9-921f-cbb3b9e8b89c.png)
3. Do not forget to add such media to the user's profile:
![image](https://user-images.githubusercontent.com/238149/54482751-7bee1300-4859-11e9-912d-941bacab00dc.png)

It's just an example. 
You can manipulate with different keys and settings for different people and groups.

**Comment by ableev** [comment]
@jvgenderen please try

**Comment by jvgenderen** [comment]
Hi Ableev. sorry for the delayed reply.
i updated the script from git and tried.
 it works.
thanks.

**Comment by ableev** [comment]
Name's Ilya, but who cares

**Comment by pablosouza10** [comment]
Great, exactly what I was looking for.
