### ISSUE TITLE
Displaying a graph from {EVENT.TIME} to {EVENT.RECOVERY.TIME}

### ISSUE THREAD

**Issue by Obskuro** [ableev/Zabbix-in-Telegram#99]
On closed problems, I would like to see a graph for the period from "{EVENT.TIME}" to "{EVENT.RECOVERY.TIME}"
https://pastebin.com/DRf5HUD5

and message in zabbix
zbxtg;graphs
zbxtg;graphs_period_start={EVENT.TIME}_{EVENT.DATE}
zbxtg;graphs_period_finish={EVENT.RECOVERY.TIME}_{EVENT.RECOVERY.DATE}
zbxtg;graphs_period={EVENT.AGE}
zbxtg;itemid:{ITEM.ID1}
zbxtg;title:{HOST.HOST}

**Comment by ableev** [comment]
Took from 2.2:
`./src/libs/zbxcommon/str.c`
```
2139 char    *zbx_age2str(int age)
2140 {
2141     size_t      offset = 0;
2142     int     days, hours, minutes;
2143     static char buffer[32];
2144
2145     days = (int)((double)age / SEC_PER_DAY);
2146     hours = (int)((double)(age - days * SEC_PER_DAY) / SEC_PER_HOUR);
2147     minutes = (int)((double)(age - days * SEC_PER_DAY - hours * SEC_PER_HOUR) / SEC_PER_MIN);
2148
2149     if (0 != days)
2150         offset += zbx_snprintf(buffer + offset, sizeof(buffer) - offset, "%dd ", days);
2151     if (0 != days || 0 != hours)
2152         offset += zbx_snprintf(buffer + offset, sizeof(buffer) - offset, "%dh ", hours);
2153     offset += zbx_snprintf(buffer + offset, sizeof(buffer) - offset, "%dm", minutes);
2154
2155     return buffer;
2156 }
```
Easy!

**Comment by ableev** [comment]
Usage:
```
zbxtg;graphs_age:{EVENT.AGE}
```
In that case, "graphs_period" will be ignored.

**Comment by ableev** [comment]
@Obskuro please, test.

**Comment by Obskuro** [comment]
It works!
Now it remains to overcome laziness - to change the already set up alerts very lazily.
